export const articles = [
  {
    slug: 'comment-connaitre-son-type-de-peau',
    title: 'Comment connaître son type de peau en 30 secondes ?',
    metaTitle: 'Comment connaître son type de peau en 30 secondes | Rate My Skin',
    metaDescription: 'Peau grasse, mixte, sèche ou sensible ? Apprenez à identifier votre vrai type de peau avec ce guide simple et notre analyse IA gratuite.',
    keyword: 'type de peau',
    excerpt: 'Normale, sèche, grasse ou mixte ? Identifier son type de peau est la première étape pour soigner sa peau efficacement. Guide complet avec test maison.',
    readingTime: 6,
    publishedAt: '2026-05-10',
    category: 'Bases Skincare',
    content: [
      { type: 'p', html: 'Vous utilisez les mauvais produits depuis des années sans le savoir&nbsp;? Vous n\'êtes pas seul(e). La plupart des problèmes de peau — imperfections persistantes, sécheresse, brillance excessive, irritations — viennent d\'une méconnaissance de son propre type de peau. Pourtant, tout part de là. Connaître son type de peau, c\'est la base absolue de tout soin efficace.' },
      { type: 'h2', text: 'Les 4 types de peau principaux' },
      { type: 'p', html: 'La dermatologie distingue quatre types de peau fondamentaux. La grande majorité des peaux rentrent dans l\'une de ces catégories, ou dans un mélange de plusieurs.' },
      { type: 'h3', text: 'La peau normale' },
      { type: 'p', html: 'La peau normale présente peu d\'imperfections, un teint uniforme, des pores peu visibles et un bon équilibre entre hydratation et production de sébum. Elle ne tire pas, ne brille pas excessivement, et tolère bien la plupart des produits cosmétiques. Si vous vous levez le matin avec une peau confortable, sans brillance ni tiraillement, vous avez probablement une peau normale.' },
      { type: 'h3', text: 'La peau sèche' },
      { type: 'p', html: 'La peau sèche produit moins de sébum que la normale et a du mal à retenir l\'humidité. Elle peut paraître terne, présenter des zones rugueuses ou squameuses, et des rougeurs. Les tiraillements après le nettoyage sont caractéristiques. À long terme, les peaux sèches ont tendance à montrer les signes de l\'âge plus tôt — d\'où l\'importance d\'une hydratation régulière et intensive.' },
      { type: 'highlight', html: '<strong>Signe révélateur :</strong> si votre peau tire après vous être lavé(e) le visage — même à l\'eau claire — vous avez très probablement une peau sèche ou déshydratée.' },
      { type: 'h3', text: 'La peau grasse' },
      { type: 'p', html: 'La peau grasse produit trop de sébum. Elle brille, a des pores dilatés, et a tendance aux points noirs, comédons et imperfections. Bonne nouvelle&nbsp;: elle vieillit souvent moins vite grâce à cette lubrification naturelle. L\'erreur classique est de sur-nettoyer pour éliminer le gras — ce qui déclenche un effet rebond et aggrave la production de sébum.' },
      { type: 'h3', text: 'La peau mixte' },
      { type: 'p', html: 'Le type de peau le plus fréquent. La zone T (front, nez, menton) est grasse, tandis que les joues sont normales à sèches. La peau mixte demande une approche en deux temps&nbsp;: des produits matifiants sur la zone T, hydratants sur les joues.' },
      { type: 'h2', text: 'Comment identifier son type de peau à la maison' },
      { type: 'h3', text: 'Le test du papier absorbant (méthode de référence)' },
      { type: 'p', html: 'C\'est la méthode la plus fiable pour un auto-diagnostic rapide.' },
      { type: 'ul', items: [
        'Nettoyez votre visage avec un nettoyant doux, sans rien appliquer après',
        'Attendez 30 minutes dans une pièce à température normale',
        'Tamponnez différentes zones (front, nez, joues, menton) avec une feuille de papier absorbant',
        'Observez la quantité de sébum sur le papier',
      ]},
      { type: 'p', html: '<strong>Interprétation :</strong> beaucoup de gras sur toutes les zones → peau grasse. Aucun gras + tiraillements → peau sèche. Gras seulement sur la zone T → peau mixte. Peu de gras, pas d\'inconfort → peau normale.' },
      { type: 'h3', text: 'L\'observation visuelle au réveil' },
      { type: 'p', html: 'Regardez votre peau une heure après le nettoyage, sans appliquer de produit. Des pores visibles sur le nez et le front, une brillance&nbsp;? Probable peau grasse ou mixte. Des zones qui tirent ou paraissent ternes&nbsp;? Peau sèche. Un aspect mat uniforme sans inconfort&nbsp;? Peau normale.' },
      { type: 'h2', text: 'La peau sensible : un type de peau à part ?' },
      { type: 'p', html: 'La sensibilité n\'est pas un type de peau au sens strict — c\'est une caractéristique qui peut s\'ajouter à n\'importe quel type. Une peau grasse peut être sensible, tout comme une peau sèche. La peau sensible réagit aux changements de température, aux parfums, à l\'alcool dans les produits, au soleil ou au stress. Elle peut rougir, piquer ou brûler sans raison apparente.' },
      { type: 'highlight', html: 'Si vous avez une peau sensible, privilégiez systématiquement les produits <strong>sans parfum, sans alcool</strong>, testés dermatologiquement et sur peaux sensibles.' },
      { type: 'h2', text: 'Pourquoi votre type de peau peut changer' },
      { type: 'p', html: 'Votre type de peau n\'est pas figé pour la vie. Il évolue avec&nbsp;:' },
      { type: 'ul', items: [
        'Les saisons (la peau est souvent plus sèche en hiver, plus grasse en été)',
        'L\'âge (la production de sébum diminue naturellement avec le temps)',
        'Les hormones (grossesse, contraception, ménopause)',
        'Le stress chronique',
        'L\'alimentation et l\'hydratation',
      ]},
      { type: 'p', html: 'Réévaluer son type de peau tous les 6 à 12 mois est une bonne pratique, surtout si votre mode de vie ou votre routine a changé.' },
      { type: 'product', name: 'The Ordinary Niacinamide 10% + Zinc 1%', description: 'Idéal pour les peaux grasses et mixtes, ce sérum abordable régule le sébum et resserre visiblement les pores en quelques semaines.', price: '~6 €', link: 'https://www.amazon.fr/s?k=The+Ordinary+Niacinamide+10+Zinc&tag=ratemyskin-21' },
      { type: 'product', name: 'CeraVe Crème Hydratante Visage', description: 'Pour les peaux sèches et normales, cette crème légère et non comédogène hydrate durablement sans jamais alourdir la peau.', price: '~14 €', link: 'https://www.amazon.fr/s?k=CeraVe+Crème+Hydratante+Visage&tag=ratemyskin-21' },
      { type: 'h2', text: 'Aller plus loin avec l\'analyse IA' },
      { type: 'p', html: 'Les méthodes maison donnent une première orientation, mais elles ont leurs limites. Elles ne permettent pas de distinguer une peau sèche d\'une peau déshydratée, de détecter une sensibilité sous-jacente, ni d\'identifier des problèmes comme une hyperpigmentation débutante ou un microbiome déséquilibré.' },
      { type: 'p', html: 'En analysant une simple photo de votre visage, l\'IA de <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> identifie votre type de peau avec précision, détecte vos 3 principaux problèmes cutanés et génère une routine personnalisée — en 30 secondes. Essayez aussi nos articles sur la <a href="/blog/routine-skincare-debutant" style="color:#A87449;">routine skincare pour débutant</a> ou sur le <a href="/blog/meilleur-serum-niacinamide" style="color:#A87449;">niacinamide</a>.' },
      { type: 'cta' },
    ],
  },

  {
    slug: 'routine-skincare-debutant',
    title: 'Routine skincare pour débutant : guide complet 2026',
    metaTitle: 'Routine skincare débutant : par où commencer en 4 étapes | Rate My Skin',
    metaDescription: 'Nouvelle dans la skincare ? Voici la routine simple et efficace pour démarrer sans se tromper. 4 étapes essentielles pour une belle peau.',
    keyword: 'routine skincare',
    excerpt: 'Nettoyant, sérum, hydratant, SPF… Par où commencer quand on débute en skincare ? Ce guide complet vous donne une routine simple et efficace, étape par étape.',
    readingTime: 7,
    publishedAt: '2026-05-12',
    category: 'Routine',
    content: [
      { type: 'p', html: 'Le monde du skincare peut sembler intimidant&nbsp;: des dizaines de produits, des ingrédients incompréhensibles, des routines en 10 étapes qui ressemblent à des rituels de laboratoire. Pourtant, une bonne routine skincare n\'a pas besoin d\'être complexe. En réalité, 3 à 5 produits bien choisis suffisent pour obtenir des résultats visibles.' },
      { type: 'h2', text: 'Pourquoi avoir une routine skincare ?' },
      { type: 'p', html: 'La peau est notre plus grande barrière de protection contre le monde extérieur. Elle subit chaque jour des agressions&nbsp;: pollution, UV, stress, fluctuations hormonales, changements de température. Une routine régulière lui permet de maintenir son équilibre, de se régénérer la nuit, et de vieillir en meilleure santé.' },
      { type: 'p', html: 'La clé est la <strong>régularité</strong>, pas la complexité. Une routine simple appliquée chaque jour vaut infiniment mieux qu\'une routine élaborée abandonnée après deux semaines.' },
      { type: 'h2', text: 'Les 3 étapes indispensables' },
      { type: 'h3', text: '1. Le nettoyage : la base de tout' },
      { type: 'p', html: 'Le nettoyage élimine les impuretés, le sébum en excès, la pollution et les résidus de produits accumulés au cours de la journée. Sans nettoyage efficace, les produits appliqués ensuite ne peuvent pas pénétrer correctement.' },
      { type: 'p', html: 'Choisissez un nettoyant adapté à votre type de peau&nbsp;:' },
      { type: 'ul', items: [
        'Peau sèche ou sensible → mousse douce ou lait nettoyant sans sulfates agressifs',
        'Peau grasse ou mixte → gel nettoyant purifiant avec acide salicylique ou zinc',
        'Peau normale → nettoyant en mousse légère ou en gel doux',
      ]},
      { type: 'highlight', html: '<strong>Règle d\'or :</strong> ne lavez jamais votre visage avec du savon pour le corps — son pH est trop alcalin et détruit le film hydrolipidique cutané.' },
      { type: 'h3', text: '2. L\'hydratation : un incontournable pour tous' },
      { type: 'p', html: 'Même les peaux grasses ont besoin d\'hydratation. La confusion vient souvent de l\'amalgame entre sébum (gras) et eau (hydratation). Vous pouvez avoir une peau grasse ET déshydratée. Un bon hydratant compense les pertes en eau sans nécessairement ajouter du gras.' },
      { type: 'ul', items: [
        'Peau sèche → crème riche avec céramides, acide hyaluronique, beurre de karité',
        'Peau grasse → gel hydratant léger, non comédogène',
        'Peau mixte → lotion ou fluide léger, plus généreux sur les zones sèches',
        'Peau sensible → formule sans parfum, sans alcool, avec de l\'allantoïne ou de la centella asiatica',
      ]},
      { type: 'h3', text: '3. La protection solaire : l\'anti-âge numéro 1' },
      { type: 'p', html: 'Le SPF est le seul soin qui a été scientifiquement prouvé pour prévenir le vieillissement cutané et les cancers de la peau. 80% du vieillissement visible du visage est causé par les UV — même par temps nuageux. Et pourtant, c\'est l\'étape que la plupart des gens négligent.' },
      { type: 'p', html: 'Appliquez une crème solaire SPF 30 minimum chaque matin, <strong>toute l\'année</strong>. Pour tout savoir sur la protection solaire, consultez notre guide&nbsp;: <a href="/blog/proteger-peau-soleil" style="color:#A87449;">comment protéger sa peau du soleil</a>.' },
      { type: 'h2', text: 'La routine du matin (5 minutes)' },
      { type: 'ul', items: [
        '① Nettoyant doux (ou simplement de l\'eau si votre peau n\'a pas transpiré la nuit)',
        '② Sérum vitamin C (optionnel, mais excellent antioxydant le matin)',
        '③ Hydratant léger',
        '④ Crème solaire SPF 30 à 50',
      ]},
      { type: 'h2', text: 'La routine du soir (10 minutes)' },
      { type: 'ul', items: [
        '① Démaquillant ou huile nettoyante (si vous portez du maquillage ou SPF)',
        '② Nettoyant doux',
        '③ Traitement ciblé (sérum niacinamide, acide hyaluronique, rétinol si vous en utilisez)',
        '④ Hydratant plus riche qu\'au matin',
      ]},
      { type: 'p', html: 'La nuit, la peau est en mode réparation. C\'est le moment idéal pour appliquer des actifs comme le rétinol ou les acides — jamais le matin, car ils augmentent la photosensibilité.' },
      { type: 'h2', text: 'Les erreurs classiques à éviter quand on débute' },
      { type: 'ul', items: [
        'Changer de produits trop souvent (laissez au moins 4 semaines pour voir les effets)',
        'Empiler trop d\'actifs dès le départ (un seul produit actif à la fois)',
        'Négliger le SPF en automne et en hiver',
        'Utiliser de l\'eau trop chaude (elle abîme la barrière cutanée)',
        'Penser que plus c\'est cher, plus c\'est efficace',
      ]},
      { type: 'product', name: 'CeraVe Hydrating Facial Cleanser', description: 'Un nettoyant doux avec céramides et acide hyaluronique, sans savon ni sulfates agressifs. Idéal pour tous les types de peaux, y compris les peaux sèches et sensibles.', price: '~10 €', link: 'https://www.amazon.fr/s?k=CeraVe+Hydrating+Facial+Cleanser&tag=ratemyskin-21' },
      { type: 'product', name: 'Neutrogena Hydro Boost Gel-Crème', description: 'Hydratant léger à l\'acide hyaluronique, non comédogène. Parfait pour les peaux normales à grasses qui cherchent une hydratation sans lourdeur.', price: '~16 €', link: 'https://www.amazon.fr/s?k=Neutrogena+Hydro+Boost+Gel+Crème&tag=ratemyskin-21' },
      { type: 'product', name: 'La Roche-Posay Anthelios SPF 50+', description: 'L\'une des meilleures crèmes solaires du marché. Texture légère, sans traces blanches, résistante à la transpiration. La référence dermato.', price: '~15 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Anthelios+SPF50&tag=ratemyskin-21' },
      { type: 'h2', text: 'Comment aller plus loin avec une routine personnalisée' },
      { type: 'p', html: 'Une fois les bases maîtrisées, la vraie question est&nbsp;: quels actifs ajouter pour traiter <em>vos</em> problèmes spécifiques&nbsp;? Acné, taches, rides, pores dilatés — chaque préoccupation a sa solution. Mais avant d\'investir dans des sérums actifs, encore faut-il savoir exactement ce dont votre peau a besoin.' },
      { type: 'p', html: 'C\'est ce que fait <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> en 30 secondes — analyser votre peau, identifier vos 3 problèmes prioritaires et vous proposer une routine sur mesure. Consultez aussi notre article sur le <a href="/blog/meilleur-serum-niacinamide" style="color:#A87449;">niacinamide</a>, l\'actif multi-bénéfices qui s\'intègre parfaitement dans toute routine débutante.' },
      { type: 'cta' },
    ],
  },

  {
    slug: 'acne-adulte-solutions',
    title: 'Acné adulte : les vraies solutions qui marchent',
    metaTitle: 'Acné adulte : 5 solutions efficaces qui marchent vraiment | Rate My Skin',
    metaDescription: 'Acné à 25, 30 ou 40 ans ? Découvrez les vraies causes et les solutions skincare adaptées à la peau adulte. Routine complète et conseils dermato.',
    keyword: 'acné adulte',
    excerpt: 'L\'acné ne touche pas que les adolescents. 25% des femmes adultes en souffrent. Découvrez les causes réelles et les solutions qui fonctionnent vraiment.',
    readingTime: 6,
    publishedAt: '2026-05-13',
    category: 'Problèmes de peau',
    content: [
      { type: 'p', html: 'L\'acné à l\'âge adulte est plus fréquente qu\'on ne le croit. Selon les études dermatologiques, près de 25% des femmes et 12% des hommes en souffrent après 25 ans. Et contrairement à l\'acné adolescente — souvent diffuse — l\'acné adulte se manifeste surtout sur le bas du visage&nbsp;: menton, mâchoire, cou. Elle est souvent hormonale, inflammatoire, et résiste aux traitements classiques conçus pour les adolescents.' },
      { type: 'h2', text: 'Pourquoi fait-on de l\'acné à l\'âge adulte ?' },
      { type: 'h3', text: 'Les fluctuations hormonales' },
      { type: 'p', html: 'Les hormones androgènes (testostérone, DHT) stimulent les glandes sébacées et favorisent la formation de comédons. Chez les femmes adultes, les poussées surviennent souvent de façon cyclique, avant les règles, lors d\'un changement de contraception, pendant la grossesse ou à l\'approche de la ménopause.' },
      { type: 'h3', text: 'Le stress chronique' },
      { type: 'p', html: 'Le stress déclenche la production de cortisol, qui à son tour stimule les glandes sébacées. Une période de stress intense (surmenage, événement de vie difficile) peut suffire à déclencher une poussée même chez quelqu\'un qui n\'en faisait pas. C\'est souvent frustrant car on cherche un coupable côté crèmes, alors que la cause est ailleurs.' },
      { type: 'h3', text: 'L\'alimentation : une influence réelle' },
      { type: 'p', html: 'Le lien entre alimentation et acné est désormais établi scientifiquement. Les aliments à index glycémique élevé (sucre, pain blanc, sodas) et les produits laitiers — surtout le lait écrémé — ont été associés à une aggravation de l\'acné dans plusieurs études. Ce n\'est pas universel, mais si vous avez une acné persistante, tester une réduction de ces aliments pendant 4 semaines vaut la peine.' },
      { type: 'h3', text: 'Les produits cosmétiques comédogènes' },
      { type: 'p', html: 'Certains ingrédients dans les soins ou le maquillage bouchent les pores et favorisent les comédons. Les principaux suspects&nbsp;: lanoline, huile de coco, isopropyl myristate, D&C Red dyes. Vérifiez systématiquement que vos produits sont <strong>non comédogènes</strong> — c\'est indiqué sur l\'emballage.' },
      { type: 'h2', text: 'Les ingrédients qui fonctionnent vraiment' },
      { type: 'p', html: 'Le marché regorge de promesses. Voici les actifs dont l\'efficacité contre l\'acné adulte est scientifiquement documentée&nbsp;:' },
      { type: 'ul', items: [
        '<strong>Acide salicylique (BHA)</strong> — pénètre dans les pores et dissout les comédons de l\'intérieur. Idéal pour les points noirs et les pores bouchés.',
        '<strong>Niacinamide</strong> — réduit l\'inflammation, régule le sébum et atténue les marques post-acné. Très bien toléré, même sur peaux sensibles. Lire notre article&nbsp;: <a href="/blog/meilleur-serum-niacinamide" style="color:#A87449;">meilleur sérum niacinamide</a>.',
        '<strong>Peroxyde de benzoyle</strong> — antibactérien puissant, efficace contre Cutibacterium acnes. À utiliser avec précaution (peut dessécher).',
        '<strong>Rétinol / trétinoïne</strong> — accélère le renouvellement cellulaire, débouche les pores, réduit les cicatrices. La trétinoïne (sur ordonnance) est l\'actif le plus prouvé contre l\'acné modérée à sévère.',
        '<strong>Acide azélaïque</strong> — anti-inflammatoire, antibactérien, et éclaircissant. Parfait pour l\'acné adulte avec hyperpigmentation post-inflammatoire.',
      ]},
      { type: 'h2', text: 'La routine anti-acné adulte (sans dessécher la peau)' },
      { type: 'p', html: 'L\'erreur la plus fréquente est de sur-traiter&nbsp;: nettoyer agressivement, empiler les actifs, dessécher la peau... qui réagit en produisant encore plus de sébum. Une routine anti-acné efficace doit être douce.' },
      { type: 'ul', items: [
        '<strong>Matin&nbsp;:</strong> nettoyant doux → niacinamide (sérum) → hydratant léger non comédogène → SPF 50',
        '<strong>Soir&nbsp;:</strong> nettoyant à l\'acide salicylique (2-3 fois par semaine) → acide azélaïque ou rétinol (en alternance, pas ensemble) → hydratant',
        '<strong>Hebdomadaire&nbsp;:</strong> masque à l\'argile sur la zone T pour absorber l\'excès de sébum',
      ]},
      { type: 'highlight', html: '<strong>Important :</strong> le rétinol et l\'acide salicylique augmentent la sensibilité au soleil. Ne les appliquez que le soir, et portez toujours un SPF le matin.' },
      { type: 'h2', text: 'Ce qu\'il ne faut surtout pas faire' },
      { type: 'ul', items: [
        'Percer les boutons (cicatrices garanties et propagation des bactéries)',
        'Changer de produits toutes les semaines (la peau a besoin de 4 à 8 semaines pour s\'adapter)',
        'Utiliser du dentifrice ou du citron (mythes inefficaces et irritants)',
        'Surcharger de produits pour compenser (moins c\'est plus en acné adulte)',
        'Négliger le SPF sous prétexte que le soleil "assèche" les boutons (faux — il aggrave les cicatrices)',
      ]},
      { type: 'product', name: 'La Roche-Posay Effaclar Duo+', description: 'Le traitement de référence contre l\'acné adulte légère à modérée. Acide salicylique + LHA + niacinamide dans une formule non comédogène testée dermatologiquement.', price: '~18 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Effaclar+Duo&tag=ratemyskin-21' },
      { type: 'product', name: 'Paula\'s Choice Skin Perfecting 2% BHA', description: 'L\'exfoliant BHA le plus plébiscité par les dermatologues et les experts skincare. Désincruste les pores en profondeur sans irriter.', price: '~30 €', link: 'https://www.amazon.fr/s?k=Paula+Choice+2+BHA+Liquid&tag=ratemyskin-21' },
      { type: 'h2', text: 'Quand consulter un dermatologue ?' },
      { type: 'p', html: 'Si votre acné est sévère (nombreux nodules ou kystes), laisse des cicatrices permanentes ou n\'a pas répondu à un traitement de soin après 3 mois, consultez un dermatologue. Il pourra vous prescrire de la trétinoïne, un antibiotique topique, ou évaluer si un traitement hormonal est approprié.' },
      { type: 'p', html: 'Pour commencer, identifier précisément vos problèmes cutanés est une bonne première étape. <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> analyse votre peau en 30 secondes et vous indique si vos préoccupations relèvent d\'une acné légère traitable à domicile ou nécessitent une consultation. Découvrez aussi nos guides&nbsp;: <a href="/blog/comment-connaitre-son-type-de-peau" style="color:#A87449;">identifier son type de peau</a> et <a href="/blog/routine-skincare-debutant" style="color:#A87449;">routine skincare débutant</a>.' },
      { type: 'cta' },
    ],
  },

  {
    slug: 'meilleur-serum-niacinamide',
    title: 'Niacinamide : le meilleur sérum pour votre peau',
    metaTitle: 'Meilleur sérum niacinamide : guide complet et top 5 produits | Rate My Skin',
    metaDescription: 'Quel sérum niacinamide choisir en 2026 ? Bienfaits, dosage idéal, comment l\'appliquer et notre sélection des meilleurs produits testés.',
    keyword: 'niacinamide',
    excerpt: 'Le niacinamide est l\'actif skincare du moment — et pour de bonnes raisons. Pores dilatés, sébum, taches, éclat : il traite tout ça à la fois. Guide complet.',
    readingTime: 5,
    publishedAt: '2026-05-14',
    category: 'Ingrédients',
    content: [
      { type: 'p', html: 'Si vous ne devez choisir qu\'un seul sérum actif pour démarrer votre routine skincare, choisissez le niacinamide. Polyvalent, bien toléré, abordable et scientifiquement prouvé — c\'est l\'un des rares ingrédients qui mérite vraiment son statut d\'incontournable.' },
      { type: 'h2', text: 'C\'est quoi le niacinamide ?' },
      { type: 'p', html: 'Le niacinamide, aussi appelé vitamine B3 ou nicotinamide, est une vitamine hydrosoluble essentielle au métabolisme cellulaire. Appliqué sur la peau, il agit comme un régulateur multi-tâche&nbsp;: il renforce la barrière cutanée, réduit l\'inflammation, régule la production de sébum et interfère avec la synthèse de mélanine (pigmentation).' },
      { type: 'p', html: 'Ce n\'est pas un actif "miracle" — la peau est complexe et aucun ingrédient ne fait des miracles seul. Mais le niacinamide est l\'un des actifs les plus <em>polyvalents</em> et les plus <em>bien tolérés</em>, ce qui en fait un excellent choix pour presque tous les types de peaux.' },
      { type: 'h2', text: 'Les bienfaits prouvés du niacinamide' },
      { type: 'ul', items: [
        '<strong>Régulation du sébum</strong> — réduit la production de sébum de 30 à 50% selon les études, idéal pour les peaux grasses et mixtes',
        '<strong>Réduction de l\'apparence des pores</strong> — en régulant le sébum, les pores paraissent moins dilatés',
        '<strong>Uniformisation du teint</strong> — inhibe le transfert de mélanine vers les cellules de surface, réduisant les taches et l\'hyperpigmentation',
        '<strong>Renforcement de la barrière cutanée</strong> — stimule la production de céramides, lipides essentiels à la barrière cutanée',
        '<strong>Effet anti-inflammatoire</strong> — réduit les rougeurs, apaise les peaux acnéiques et sensibles',
        '<strong>Action anti-âge</strong> — stimule la production de collagène et atténue les ridules superficielles',
      ]},
      { type: 'highlight', html: 'Le niacinamide est l\'un des seuls actifs qui convient à <strong>tous les types de peaux</strong> — sèche, grasse, mixte, sensible, mature. C\'est rare.' },
      { type: 'h2', text: 'Comment utiliser le niacinamide' },
      { type: 'p', html: 'La concentration optimale se situe entre <strong>5% et 10%</strong>. En dessous de 5%, les effets sont limités. Au-dessus de 10%, le risque d\'irritation augmente sans bénéfice supplémentaire prouvé.' },
      { type: 'ul', items: [
        'Appliquez matin et/ou soir, après le nettoyage et avant l\'hydratant',
        'Quelques gouttes suffisent — le niacinamide se répartit facilement',
        'Il peut être utilisé tous les jours, y compris sous le SPF le matin',
        'Commencez à une application par jour si vous avez une peau sensible',
      ]},
      { type: 'h2', text: 'Les meilleurs sérums à la niacinamide' },
      { type: 'product', name: 'The Ordinary Niacinamide 10% + Zinc 1%', description: 'Le rapport qualité-prix imbattable. 10% de niacinamide + zinc pour réguler le sébum et réduire les imperfections. La référence accessible.', price: '~6 €', link: 'https://www.amazon.fr/s?k=The+Ordinary+Niacinamide+10+Zinc+1&tag=ratemyskin-21' },
      { type: 'product', name: 'La Roche-Posay Toleriane Sérum Niacinamide', description: 'Formule dermatologiquement testée avec 10% de niacinamide pur. Plus chère mais idéale pour les peaux ultra-sensibles qui réagissent aux formules basiques.', price: '~22 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Toleriane+sérum+niacinamide&tag=ratemyskin-21' },
      { type: 'h2', text: 'Niacinamide et vitamine C : peut-on les mélanger ?' },
      { type: 'p', html: 'Longtemps, on a cru que mélanger niacinamide et vitamine C créait du niacine — une substance qui provoque des rougeurs. C\'est un mythe. Des études récentes montrent que cette réaction ne se produit pas dans les conditions d\'utilisation normale.' },
      { type: 'p', html: 'Cependant, la vitamine C pure (acide ascorbique) est une molécule instable qui s\'oxyde facilement. Pour maximiser leurs effets respectifs, l\'idéal est de les appliquer à des moments différents&nbsp;: vitamine C le matin (antioxydant contre les UV), niacinamide le soir. Mais les appliquer ensemble n\'est pas dangereux.' },
      { type: 'h2', text: 'Pour qui est fait le niacinamide ?' },
      { type: 'p', html: 'Pour (presque) tout le monde&nbsp;:' },
      { type: 'ul', items: [
        'Peau grasse → régule le sébum et réduit les pores',
        'Peau acnéique → anti-inflammatoire et réduit les marques post-acné',
        'Peau terne avec taches → uniformise le teint',
        'Peau sensible → renforce la barrière, bien toléré',
        'Peau mature → action anti-âge légère',
      ]},
      { type: 'p', html: 'Le seul cas où le niacinamide peut poser problème&nbsp;: une allergie à la niacine (vitamine B3) — extrêmement rare. Si vous avez une rougeur intense ou des picotements marqués à l\'application, c\'est peut-être votre cas. Faites toujours un patch test à l\'intérieur du poignet 24h avant d\'appliquer sur le visage.' },
      { type: 'p', html: 'Pour savoir si le niacinamide est l\'actif dont votre peau a besoin en priorité, une analyse <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> identifie vos problèmes cutanés spécifiques et vous recommande les actifs les plus pertinents. Voir aussi&nbsp;: <a href="/blog/acne-adulte-solutions" style="color:#A87449;">acné adulte</a>, <a href="/blog/routine-skincare-debutant" style="color:#A87449;">routine skincare débutant</a>.' },
      { type: 'cta' },
    ],
  },

  {
    slug: 'proteger-peau-soleil',
    title: 'Comment protéger sa peau du soleil (guide expert)',
    metaTitle: 'Protéger sa peau du soleil : guide SPF complet 2026 | Rate My Skin',
    metaDescription: 'Comment vraiment protéger sa peau du soleil ? SPF 30 ou 50, application, réapplication, meilleurs solaires visage. Tous les conseils essentiels.',
    keyword: 'protection solaire',
    excerpt: 'La protection solaire est l\'anti-âge le plus efficace qui existe. Et pourtant, la plupart d\'entre nous l\'appliquent mal. Guide complet sur le SPF.',
    readingTime: 6,
    publishedAt: '2026-05-15',
    category: 'Protection',
    content: [
      { type: 'p', html: 'Voici un chiffre qui devrait tout changer&nbsp;: <strong>80% du vieillissement visible du visage est causé par les UV</strong> — rides, taches, perte d\'éclat, peau flasque. C\'est ce que les chercheurs appellent le photo-vieillissement. Et la bonne nouvelle&nbsp;: c\'est en grande partie évitable avec un produit simple, peu cher, et disponible partout. La crème solaire.' },
      { type: 'p', html: 'Pourtant, la majorité des Français n\'appliquent du SPF qu\'en été, à la plage. C\'est insuffisant. Les UV traversent les nuages, les vitres de voiture, et agissent même par temps couvert. La protection solaire quotidienne est, sans exagérer, le geste anti-âge le plus efficace qui existe.' },
      { type: 'h2', text: 'UVA vs UVB : comprendre la différence' },
      { type: 'p', html: 'Le spectre solaire comporte deux types de rayonnements UV qui atteignent notre peau&nbsp;:' },
      { type: 'ul', items: [
        '<strong>UVB</strong> — responsables des coups de soleil, de la production de vitamine D, et des cancers de la peau. Leur intensité varie avec la saison et l\'heure.',
        '<strong>UVA</strong> — pénètrent plus profondément dans le derme. Responsables du vieillissement cutané et des taches. Leur intensité est quasi constante toute l\'année, toute la journée, même par temps nuageux.',
      ]},
      { type: 'p', html: 'Le chiffre SPF (ex&nbsp;: SPF 50) mesure uniquement la protection contre les UVB. Pour être protégé des UVA, cherchez un produit avec la mention "<strong>large spectre</strong>" ou le logo UVA dans un cercle — c\'est obligatoire sur les crèmes solaires conformes aux standards européens.' },
      { type: 'h2', text: 'Filtres minéraux vs filtres chimiques : lequel choisir ?' },
      { type: 'h3', text: 'Les filtres minéraux (physiques)' },
      { type: 'p', html: 'Oxyde de zinc et dioxyde de titane. Ils agissent comme un miroir&nbsp;: ils reflètent et dispersent les UV avant qu\'ils ne pénètrent dans la peau. Ils sont efficaces immédiatement à l\'application, bien tolérés sur les peaux sensibles et les peaux acnéiques. Inconvénient&nbsp;: texture parfois plus épaisse, effet "masque blanc" sur les peaux foncées (bien que les formulations modernes aient considérablement amélioré ce point).' },
      { type: 'h3', text: 'Les filtres chimiques (organiques)' },
      { type: 'p', html: 'Avobenzone, oxybenzone, tinosorb, mexoryl… Ils absorbent les UV et les convertissent en chaleur. Textures légères, invisibles sur tous les phototypes, souvent plus agréables à porter au quotidien. Certains peuvent être irritants sur les peaux très sensibles. Nécessitent 20 minutes d\'attente après application pour être pleinement actifs.' },
      { type: 'highlight', html: 'La plupart des <strong>crèmes solaires modernes</strong> combinent les deux types de filtres pour maximiser la protection et améliorer la texture. Choisissez selon votre type de peau, pas selon un idéalisme ingrédients.' },
      { type: 'h2', text: 'SPF 30 ou SPF 50 : quelle différence concrète ?' },
      { type: 'p', html: 'SPF 30 bloque environ 97% des UVB. SPF 50 en bloque environ 98%. La différence est faible — mais elle compte si vous avez une peau claire, un risque de cancer élevé ou si vous êtes exposé(e) longtemps. Pour un usage quotidien en ville, SPF 30 est généralement suffisant. Pour la plage, le sport outdoor ou les peaux très claires&nbsp;: SPF 50 minimum.' },
      { type: 'h2', text: 'Comment appliquer correctement sa protection solaire' },
      { type: 'p', html: 'L\'application est aussi importante que le produit lui-même. La plupart des gens appliquent 2 à 4 fois moins de crème solaire que la quantité nécessaire pour obtenir le SPF indiqué.' },
      { type: 'ul', items: [
        'Quantité recommandée pour le visage : une demi-cuillère à café (environ 1/4 cuillère à café si vous mettez aussi le cou)',
        'Appliquer 20 minutes avant l\'exposition (surtout pour les filtres chimiques)',
        'Renouveler toutes les 2 heures en cas d\'exposition prolongée, après la baignade ou la transpiration',
        'Couvrir le contour des yeux, le nez, les oreilles et le cou — zones souvent oubliées',
      ]},
      { type: 'h2', text: 'Les erreurs les plus fréquentes' },
      { type: 'ul', items: [
        'N\'appliquer le SPF qu\'en été (les UVA agissent toute l\'année)',
        'Compter sur le SPF dans le fond de teint ou le BB cream (quantité insuffisante)',
        'Ne pas renouveler l\'application en cas d\'exposition longue',
        'Oublier les zones sensibles (oreilles, cou, lèvres)',
        'Penser que les peaux foncées n\'ont pas besoin de SPF (faux — elles vieillissent aussi et peuvent développer des cancers)',
      ]},
      { type: 'product', name: 'La Roche-Posay Anthelios Invisible Fluid SPF 50+', description: 'Texture ultra-légère, résistante à la transpiration, sans traces blanches. La référence dermato pour un usage quotidien sur tous les phototypes.', price: '~15 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Anthelios+Invisible+Fluid&tag=ratemyskin-21' },
      { type: 'product', name: 'Avène SPF 50+ Solaire Hydratant', description: 'Idéal pour les peaux sensibles et réactives. Formule apaisante à l\'eau thermale d\'Avène, filtre large spectre, très bien tolérée.', price: '~12 €', link: 'https://www.amazon.fr/s?k=Avène+SPF+50+solaire&tag=ratemyskin-21' },
      { type: 'h2', text: 'Protection solaire et vitamine D : faut-il s\'inquiéter ?' },
      { type: 'p', html: 'Un mythe courant&nbsp;: "si je mets du SPF, je ne fais plus de vitamine D". En pratique, la plupart des gens n\'appliquent pas une quantité suffisante de crème solaire pour bloquer totalement la synthèse de vitamine D. Par ailleurs, la vitamine D peut être obtenue via l\'alimentation (poissons gras, œufs, champignons) ou la supplémentation. Ne jamais sacrifier la protection solaire pour la vitamine D — ce n\'est pas un arbitrage nécessaire.' },
      { type: 'p', html: 'Pour savoir si votre peau présente des dommages solaires existants (taches, hyperpigmentation, vieillissement prématuré), <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> les détecte sur une simple photo. Consultez aussi nos guides&nbsp;: <a href="/blog/comment-connaitre-son-type-de-peau" style="color:#A87449;">connaître son type de peau</a> et <a href="/blog/routine-skincare-debutant" style="color:#A87449;">routine skincare débutant</a>.' },
      { type: 'cta' },
    ],
  },
];

export function getArticleBySlug(slug) {
  return articles.find(a => a.slug === slug) || null;
}
