export const articles = [
  {
    slug: 'comment-connaitre-son-type-de-peau',
    title: 'Comment connaître son type de peau en 30 secondes ?',
    metaTitle: 'Comment connaître son type de peau en 30 secondes | Rate My Skin',
    metaDescription: 'Peau grasse, mixte, sèche ou sensible ? Apprenez à identifier votre vrai type de peau avec ce guide simple et notre analyse IA gratuite.',
    keyword: 'type de peau',
    excerpt: 'Normale, sèche, grasse ou mixte ? Identifier son type de peau est la première étape pour soigner sa peau efficacement. Guide complet avec test maison.',
    readingTime: 6,
    publishedAt: '2026-05-10',
    category: 'Bases Skincare',
    content: [
      { type: 'p', html: 'Vous utilisez les mauvais produits depuis des années sans le savoir&nbsp;? Vous n\'êtes pas seul(e). La plupart des problèmes de peau — imperfections persistantes, sécheresse, brillance excessive, irritations — viennent d\'une méconnaissance de son propre type de peau. Pourtant, tout part de là. Connaître son type de peau, c\'est la base absolue de tout soin efficace.' },
      { type: 'h2', text: 'Les 4 types de peau principaux' },
      { type: 'p', html: 'La dermatologie distingue quatre types de peau fondamentaux. La grande majorité des peaux rentrent dans l\'une de ces catégories, ou dans un mélange de plusieurs.' },
      { type: 'h3', text: 'La peau normale' },
      { type: 'p', html: 'La peau normale présente peu d\'imperfections, un teint uniforme, des pores peu visibles et un bon équilibre entre hydratation et production de sébum. Elle ne tire pas, ne brille pas excessivement, et tolère bien la plupart des produits cosmétiques. Si vous vous levez le matin avec une peau confortable, sans brillance ni tiraillement, vous avez probablement une peau normale.' },
      { type: 'h3', text: 'La peau sèche' },
      { type: 'p', html: 'La peau sèche produit moins de sébum que la normale et a du mal à retenir l\'humidité. Elle peut paraître terne, présenter des zones rugueuses ou squameuses, et des rougeurs. Les tiraillements après le nettoyage sont caractéristiques. À long terme, les peaux sèches ont tendance à montrer les signes de l\'âge plus tôt — d\'où l\'importance d\'une hydratation régulière et intensive.' },
      { type: 'highlight', html: '<strong>Signe révélateur :</strong> si votre peau tire après vous être lavé(e) le visage — même à l\'eau claire — vous avez très probablement une peau sèche ou déshydratée.' },
      { type: 'h3', text: 'La peau grasse' },
      { type: 'p', html: 'La peau grasse produit trop de sébum. Elle brille, a des pores dilatés, et a tendance aux points noirs, comédons et imperfections. Bonne nouvelle&nbsp;: elle vieillit souvent moins vite grâce à cette lubrification naturelle. L\'erreur classique est de sur-nettoyer pour éliminer le gras — ce qui déclenche un effet rebond et aggrave la production de sébum.' },
      { type: 'h3', text: 'La peau mixte' },
      { type: 'p', html: 'Le type de peau le plus fréquent. La zone T (front, nez, menton) est grasse, tandis que les joues sont normales à sèches. La peau mixte demande une approche en deux temps&nbsp;: des produits matifiants sur la zone T, hydratants sur les joues.' },
      { type: 'h2', text: 'Comment identifier son type de peau à la maison' },
      { type: 'h3', text: 'Le test du papier absorbant (méthode de référence)' },
      { type: 'p', html: 'C\'est la méthode la plus fiable pour un auto-diagnostic rapide.' },
      { type: 'ul', items: [
        'Nettoyez votre visage avec un nettoyant doux, sans rien appliquer après',
        'Attendez 30 minutes dans une pièce à température normale',
        'Tamponnez différentes zones (front, nez, joues, menton) avec une feuille de papier absorbant',
        'Observez la quantité de sébum sur le papier',
      ]},
      { type: 'p', html: '<strong>Interprétation :</strong> beaucoup de gras sur toutes les zones → peau grasse. Aucun gras + tiraillements → peau sèche. Gras seulement sur la zone T → peau mixte. Peu de gras, pas d\'inconfort → peau normale.' },
      { type: 'h3', text: 'L\'observation visuelle au réveil' },
      { type: 'p', html: 'Regardez votre peau une heure après le nettoyage, sans appliquer de produit. Des pores visibles sur le nez et le front, une brillance&nbsp;? Probable peau grasse ou mixte. Des zones qui tirent ou paraissent ternes&nbsp;? Peau sèche. Un aspect mat uniforme sans inconfort&nbsp;? Peau normale.' },
      { type: 'h2', text: 'La peau sensible : un type de peau à part ?' },
      { type: 'p', html: 'La sensibilité n\'est pas un type de peau au sens strict — c\'est une caractéristique qui peut s\'ajouter à n\'importe quel type. Une peau grasse peut être sensible, tout comme une peau sèche. La peau sensible réagit aux changements de température, aux parfums, à l\'alcool dans les produits, au soleil ou au stress. Elle peut rougir, piquer ou brûler sans raison apparente.' },
      { type: 'highlight', html: 'Si vous avez une peau sensible, privilégiez systématiquement les produits <strong>sans parfum, sans alcool</strong>, testés dermatologiquement et sur peaux sensibles.' },
      { type: 'h2', text: 'Pourquoi votre type de peau peut changer' },
      { type: 'p', html: 'Votre type de peau n\'est pas figé pour la vie. Il évolue avec&nbsp;:' },
      { type: 'ul', items: [
        'Les saisons (la peau est souvent plus sèche en hiver, plus grasse en été)',
        'L\'âge (la production de sébum diminue naturellement avec le temps)',
        'Les hormones (grossesse, contraception, ménopause)',
        'Le stress chronique',
        'L\'alimentation et l\'hydratation',
      ]},
      { type: 'p', html: 'Réévaluer son type de peau tous les 6 à 12 mois est une bonne pratique, surtout si votre mode de vie ou votre routine a changé.' },
      { type: 'product', name: 'The Ordinary Niacinamide 10% + Zinc 1%', description: 'Idéal pour les peaux grasses et mixtes, ce sérum abordable régule le sébum et resserre visiblement les pores en quelques semaines.', price: '~6 €', link: 'https://www.amazon.fr/s?k=The+Ordinary+Niacinamide+10+Zinc&tag=ratemyskin-21' },
      { type: 'product', name: 'CeraVe Crème Hydratante Visage', description: 'Pour les peaux sèches et normales, cette crème légère et non comédogène hydrate durablement sans jamais alourdir la peau.', price: '~14 €', link: 'https://www.amazon.fr/s?k=CeraVe+Crème+Hydratante+Visage&tag=ratemyskin-21' },
      { type: 'h2', text: 'Aller plus loin avec l\'analyse IA' },
      { type: 'p', html: 'Les méthodes maison donnent une première orientation, mais elles ont leurs limites. Elles ne permettent pas de distinguer une peau sèche d\'une peau déshydratée, de détecter une sensibilité sous-jacente, ni d\'identifier des problèmes comme une hyperpigmentation débutante ou un microbiome déséquilibré.' },
      { type: 'p', html: 'En analysant une simple photo de votre visage, l\'IA de <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> identifie votre type de peau avec précision, détecte vos 3 principaux problèmes cutanés et génère une routine personnalisée — en 30 secondes. Essayez aussi nos articles sur la <a href="/blog/routine-skincare-debutant" style="color:#A87449;">routine skincare pour débutant</a> ou sur le <a href="/blog/meilleur-serum-niacinamide" style="color:#A87449;">niacinamide</a>.' },
      { type: 'cta' },
    ],
  },

  {
    slug: 'routine-skincare-debutant',
    title: 'Routine skincare pour débutant : guide complet 2026',
    metaTitle: 'Routine skincare débutant : par où commencer en 4 étapes | Rate My Skin',
    metaDescription: 'Nouvelle dans la skincare ? Voici la routine simple et efficace pour démarrer sans se tromper. 4 étapes essentielles pour une belle peau.',
    keyword: 'routine skincare',
    excerpt: 'Nettoyant, sérum, hydratant, SPF… Par où commencer quand on débute en skincare ? Ce guide complet vous donne une routine simple et efficace, étape par étape.',
    readingTime: 7,
    publishedAt: '2026-05-12',
    category: 'Routine',
    content: [
      { type: 'p', html: 'Le monde du skincare peut sembler intimidant&nbsp;: des dizaines de produits, des ingrédients incompréhensibles, des routines en 10 étapes qui ressemblent à des rituels de laboratoire. Pourtant, une bonne routine skincare n\'a pas besoin d\'être complexe. En réalité, 3 à 5 produits bien choisis suffisent pour obtenir des résultats visibles.' },
      { type: 'h2', text: 'Pourquoi avoir une routine skincare ?' },
      { type: 'p', html: 'La peau est notre plus grande barrière de protection contre le monde extérieur. Elle subit chaque jour des agressions&nbsp;: pollution, UV, stress, fluctuations hormonales, changements de température. Une routine régulière lui permet de maintenir son équilibre, de se régénérer la nuit, et de vieillir en meilleure santé.' },
      { type: 'p', html: 'La clé est la <strong>régularité</strong>, pas la complexité. Une routine simple appliquée chaque jour vaut infiniment mieux qu\'une routine élaborée abandonnée après deux semaines.' },
      { type: 'h2', text: 'Les 3 étapes indispensables' },
      { type: 'h3', text: '1. Le nettoyage : la base de tout' },
      { type: 'p', html: 'Le nettoyage élimine les impuretés, le sébum en excès, la pollution et les résidus de produits accumulés au cours de la journée. Sans nettoyage efficace, les produits appliqués ensuite ne peuvent pas pénétrer correctement.' },
      { type: 'p', html: 'Choisissez un nettoyant adapté à votre type de peau&nbsp;:' },
      { type: 'ul', items: [
        'Peau sèche ou sensible → mousse douce ou lait nettoyant sans sulfates agressifs',
        'Peau grasse ou mixte → gel nettoyant purifiant avec acide salicylique ou zinc',
        'Peau normale → nettoyant en mousse légère ou en gel doux',
      ]},
      { type: 'highlight', html: '<strong>Règle d\'or :</strong> ne lavez jamais votre visage avec du savon pour le corps — son pH est trop alcalin et détruit le film hydrolipidique cutané.' },
      { type: 'h3', text: '2. L\'hydratation : un incontournable pour tous' },
      { type: 'p', html: 'Même les peaux grasses ont besoin d\'hydratation. La confusion vient souvent de l\'amalgame entre sébum (gras) et eau (hydratation). Vous pouvez avoir une peau grasse ET déshydratée. Un bon hydratant compense les pertes en eau sans nécessairement ajouter du gras.' },
      { type: 'ul', items: [
        'Peau sèche → crème riche avec céramides, acide hyaluronique, beurre de karité',
        'Peau grasse → gel hydratant léger, non comédogène',
        'Peau mixte → lotion ou fluide léger, plus généreux sur les zones sèches',
        'Peau sensible → formule sans parfum, sans alcool, avec de l\'allantoïne ou de la centella asiatica',
      ]},
      { type: 'h3', text: '3. La protection solaire : l\'anti-âge numéro 1' },
      { type: 'p', html: 'Le SPF est le seul soin qui a été scientifiquement prouvé pour prévenir le vieillissement cutané et les cancers de la peau. 80% du vieillissement visible du visage est causé par les UV — même par temps nuageux. Et pourtant, c\'est l\'étape que la plupart des gens négligent.' },
      { type: 'p', html: 'Appliquez une crème solaire SPF 30 minimum chaque matin, <strong>toute l\'année</strong>. Pour tout savoir sur la protection solaire, consultez notre guide&nbsp;: <a href="/blog/proteger-peau-soleil" style="color:#A87449;">comment protéger sa peau du soleil</a>.' },
      { type: 'h2', text: 'La routine du matin (5 minutes)' },
      { type: 'ul', items: [
        '① Nettoyant doux (ou simplement de l\'eau si votre peau n\'a pas transpiré la nuit)',
        '② Sérum vitamin C (optionnel, mais excellent antioxydant le matin)',
        '③ Hydratant léger',
        '④ Crème solaire SPF 30 à 50',
      ]},
      { type: 'h2', text: 'La routine du soir (10 minutes)' },
      { type: 'ul', items: [
        '① Démaquillant ou huile nettoyante (si vous portez du maquillage ou SPF)',
        '② Nettoyant doux',
        '③ Traitement ciblé (sérum niacinamide, acide hyaluronique, rétinol si vous en utilisez)',
        '④ Hydratant plus riche qu\'au matin',
      ]},
      { type: 'p', html: 'La nuit, la peau est en mode réparation. C\'est le moment idéal pour appliquer des actifs comme le rétinol ou les acides — jamais le matin, car ils augmentent la photosensibilité.' },
      { type: 'h2', text: 'Les erreurs classiques à éviter quand on débute' },
      { type: 'ul', items: [
        'Changer de produits trop souvent (laissez au moins 4 semaines pour voir les effets)',
        'Empiler trop d\'actifs dès le départ (un seul produit actif à la fois)',
        'Négliger le SPF en automne et en hiver',
        'Utiliser de l\'eau trop chaude (elle abîme la barrière cutanée)',
        'Penser que plus c\'est cher, plus c\'est efficace',
      ]},
      { type: 'product', name: 'CeraVe Hydrating Facial Cleanser', description: 'Un nettoyant doux avec céramides et acide hyaluronique, sans savon ni sulfates agressifs. Idéal pour tous les types de peaux, y compris les peaux sèches et sensibles.', price: '~10 €', link: 'https://www.amazon.fr/s?k=CeraVe+Hydrating+Facial+Cleanser&tag=ratemyskin-21' },
      { type: 'product', name: 'Neutrogena Hydro Boost Gel-Crème', description: 'Hydratant léger à l\'acide hyaluronique, non comédogène. Parfait pour les peaux normales à grasses qui cherchent une hydratation sans lourdeur.', price: '~16 €', link: 'https://www.amazon.fr/s?k=Neutrogena+Hydro+Boost+Gel+Crème&tag=ratemyskin-21' },
      { type: 'product', name: 'La Roche-Posay Anthelios SPF 50+', description: 'L\'une des meilleures crèmes solaires du marché. Texture légère, sans traces blanches, résistante à la transpiration. La référence dermato.', price: '~15 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Anthelios+SPF50&tag=ratemyskin-21' },
      { type: 'h2', text: 'Comment aller plus loin avec une routine personnalisée' },
      { type: 'p', html: 'Une fois les bases maîtrisées, la vraie question est&nbsp;: quels actifs ajouter pour traiter <em>vos</em> problèmes spécifiques&nbsp;? Acné, taches, rides, pores dilatés — chaque préoccupation a sa solution. Mais avant d\'investir dans des sérums actifs, encore faut-il savoir exactement ce dont votre peau a besoin.' },
      { type: 'p', html: 'C\'est ce que fait <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> en 30 secondes — analyser votre peau, identifier vos 3 problèmes prioritaires et vous proposer une routine sur mesure. Consultez aussi notre article sur le <a href="/blog/meilleur-serum-niacinamide" style="color:#A87449;">niacinamide</a>, l\'actif multi-bénéfices qui s\'intègre parfaitement dans toute routine débutante.' },
      { type: 'cta' },
    ],
  },

  {
    slug: 'acne-adulte-solutions',
    title: 'Acné adulte : les vraies solutions qui marchent',
    metaTitle: 'Acné adulte : 5 solutions efficaces qui marchent vraiment | Rate My Skin',
    metaDescription: 'Acné à 25, 30 ou 40 ans ? Découvrez les vraies causes et les solutions skincare adaptées à la peau adulte. Routine complète et conseils dermato.',
    keyword: 'acné adulte',
    excerpt: 'L\'acné ne touche pas que les adolescents. 25% des femmes adultes en souffrent. Découvrez les causes réelles et les solutions qui fonctionnent vraiment.',
    readingTime: 6,
    publishedAt: '2026-05-13',
    category: 'Problèmes de peau',
    content: [
      { type: 'p', html: 'L\'acné à l\'âge adulte est plus fréquente qu\'on ne le croit. Selon les études dermatologiques, près de 25% des femmes et 12% des hommes en souffrent après 25 ans. Et contrairement à l\'acné adolescente — souvent diffuse — l\'acné adulte se manifeste surtout sur le bas du visage&nbsp;: menton, mâchoire, cou. Elle est souvent hormonale, inflammatoire, et résiste aux traitements classiques conçus pour les adolescents.' },
      { type: 'h2', text: 'Pourquoi fait-on de l\'acné à l\'âge adulte ?' },
      { type: 'h3', text: 'Les fluctuations hormonales' },
      { type: 'p', html: 'Les hormones androgènes (testostérone, DHT) stimulent les glandes sébacées et favorisent la formation de comédons. Chez les femmes adultes, les poussées surviennent souvent de façon cyclique, avant les règles, lors d\'un changement de contraception, pendant la grossesse ou à l\'approche de la ménopause.' },
      { type: 'h3', text: 'Le stress chronique' },
      { type: 'p', html: 'Le stress déclenche la production de cortisol, qui à son tour stimule les glandes sébacées. Une période de stress intense (surmenage, événement de vie difficile) peut suffire à déclencher une poussée même chez quelqu\'un qui n\'en faisait pas. C\'est souvent frustrant car on cherche un coupable côté crèmes, alors que la cause est ailleurs.' },
      { type: 'h3', text: 'L\'alimentation : une influence réelle' },
      { type: 'p', html: 'Le lien entre alimentation et acné est désormais établi scientifiquement. Les aliments à index glycémique élevé (sucre, pain blanc, sodas) et les produits laitiers — surtout le lait écrémé — ont été associés à une aggravation de l\'acné dans plusieurs études. Ce n\'est pas universel, mais si vous avez une acné persistante, tester une réduction de ces aliments pendant 4 semaines vaut la peine.' },
      { type: 'h3', text: 'Les produits cosmétiques comédogènes' },
      { type: 'p', html: 'Certains ingrédients dans les soins ou le maquillage bouchent les pores et favorisent les comédons. Les principaux suspects&nbsp;: lanoline, huile de coco, isopropyl myristate, D&C Red dyes. Vérifiez systématiquement que vos produits sont <strong>non comédogènes</strong> — c\'est indiqué sur l\'emballage.' },
      { type: 'h2', text: 'Les ingrédients qui fonctionnent vraiment' },
      { type: 'p', html: 'Le marché regorge de promesses. Voici les actifs dont l\'efficacité contre l\'acné adulte est scientifiquement documentée&nbsp;:' },
      { type: 'ul', items: [
        '<strong>Acide salicylique (BHA)</strong> — pénètre dans les pores et dissout les comédons de l\'intérieur. Idéal pour les points noirs et les pores bouchés.',
        '<strong>Niacinamide</strong> — réduit l\'inflammation, régule le sébum et atténue les marques post-acné. Très bien toléré, même sur peaux sensibles. Lire notre article&nbsp;: <a href="/blog/meilleur-serum-niacinamide" style="color:#A87449;">meilleur sérum niacinamide</a>.',
        '<strong>Peroxyde de benzoyle</strong> — antibactérien puissant, efficace contre Cutibacterium acnes. À utiliser avec précaution (peut dessécher).',
        '<strong>Rétinol / trétinoïne</strong> — accélère le renouvellement cellulaire, débouche les pores, réduit les cicatrices. La trétinoïne (sur ordonnance) est l\'actif le plus prouvé contre l\'acné modérée à sévère.',
        '<strong>Acide azélaïque</strong> — anti-inflammatoire, antibactérien, et éclaircissant. Parfait pour l\'acné adulte avec hyperpigmentation post-inflammatoire.',
      ]},
      { type: 'h2', text: 'La routine anti-acné adulte (sans dessécher la peau)' },
      { type: 'p', html: 'L\'erreur la plus fréquente est de sur-traiter&nbsp;: nettoyer agressivement, empiler les actifs, dessécher la peau... qui réagit en produisant encore plus de sébum. Une routine anti-acné efficace doit être douce.' },
      { type: 'ul', items: [
        '<strong>Matin&nbsp;:</strong> nettoyant doux → niacinamide (sérum) → hydratant léger non comédogène → SPF 50',
        '<strong>Soir&nbsp;:</strong> nettoyant à l\'acide salicylique (2-3 fois par semaine) → acide azélaïque ou rétinol (en alternance, pas ensemble) → hydratant',
        '<strong>Hebdomadaire&nbsp;:</strong> masque à l\'argile sur la zone T pour absorber l\'excès de sébum',
      ]},
      { type: 'highlight', html: '<strong>Important :</strong> le rétinol et l\'acide salicylique augmentent la sensibilité au soleil. Ne les appliquez que le soir, et portez toujours un SPF le matin.' },
      { type: 'h2', text: 'Ce qu\'il ne faut surtout pas faire' },
      { type: 'ul', items: [
        'Percer les boutons (cicatrices garanties et propagation des bactéries)',
        'Changer de produits toutes les semaines (la peau a besoin de 4 à 8 semaines pour s\'adapter)',
        'Utiliser du dentifrice ou du citron (mythes inefficaces et irritants)',
        'Surcharger de produits pour compenser (moins c\'est plus en acné adulte)',
        'Négliger le SPF sous prétexte que le soleil "assèche" les boutons (faux — il aggrave les cicatrices)',
      ]},
      { type: 'product', name: 'La Roche-Posay Effaclar Duo+', description: 'Le traitement de référence contre l\'acné adulte légère à modérée. Acide salicylique + LHA + niacinamide dans une formule non comédogène testée dermatologiquement.', price: '~18 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Effaclar+Duo&tag=ratemyskin-21' },
      { type: 'product', name: 'Paula\'s Choice Skin Perfecting 2% BHA', description: 'L\'exfoliant BHA le plus plébiscité par les dermatologues et les experts skincare. Désincruste les pores en profondeur sans irriter.', price: '~30 €', link: 'https://www.amazon.fr/s?k=Paula+Choice+2+BHA+Liquid&tag=ratemyskin-21' },
      { type: 'h2', text: 'Quand consulter un dermatologue ?' },
      { type: 'p', html: 'Si votre acné est sévère (nombreux nodules ou kystes), laisse des cicatrices permanentes ou n\'a pas répondu à un traitement de soin après 3 mois, consultez un dermatologue. Il pourra vous prescrire de la trétinoïne, un antibiotique topique, ou évaluer si un traitement hormonal est approprié.' },
      { type: 'p', html: 'Pour commencer, identifier précisément vos problèmes cutanés est une bonne première étape. <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> analyse votre peau en 30 secondes et vous indique si vos préoccupations relèvent d\'une acné légère traitable à domicile ou nécessitent une consultation. Découvrez aussi nos guides&nbsp;: <a href="/blog/comment-connaitre-son-type-de-peau" style="color:#A87449;">identifier son type de peau</a> et <a href="/blog/routine-skincare-debutant" style="color:#A87449;">routine skincare débutant</a>.' },
      { type: 'cta' },
    ],
  },

  {
    slug: 'meilleur-serum-niacinamide',
    title: 'Niacinamide : le meilleur sérum pour votre peau',
    metaTitle: 'Meilleur sérum niacinamide : guide complet et top 5 produits | Rate My Skin',
    metaDescription: 'Quel sérum niacinamide choisir en 2026 ? Bienfaits, dosage idéal, comment l\'appliquer et notre sélection des meilleurs produits testés.',
    keyword: 'niacinamide',
    excerpt: 'Le niacinamide est l\'actif skincare du moment — et pour de bonnes raisons. Pores dilatés, sébum, taches, éclat : il traite tout ça à la fois. Guide complet.',
    readingTime: 5,
    publishedAt: '2026-05-14',
    category: 'Ingrédients',
    content: [
      { type: 'p', html: 'Si vous ne devez choisir qu\'un seul sérum actif pour démarrer votre routine skincare, choisissez le niacinamide. Polyvalent, bien toléré, abordable et scientifiquement prouvé — c\'est l\'un des rares ingrédients qui mérite vraiment son statut d\'incontournable.' },
      { type: 'h2', text: 'C\'est quoi le niacinamide ?' },
      { type: 'p', html: 'Le niacinamide, aussi appelé vitamine B3 ou nicotinamide, est une vitamine hydrosoluble essentielle au métabolisme cellulaire. Appliqué sur la peau, il agit comme un régulateur multi-tâche&nbsp;: il renforce la barrière cutanée, réduit l\'inflammation, régule la production de sébum et interfère avec la synthèse de mélanine (pigmentation).' },
      { type: 'p', html: 'Ce n\'est pas un actif "miracle" — la peau est complexe et aucun ingrédient ne fait des miracles seul. Mais le niacinamide est l\'un des actifs les plus <em>polyvalents</em> et les plus <em>bien tolérés</em>, ce qui en fait un excellent choix pour presque tous les types de peaux.' },
      { type: 'h2', text: 'Les bienfaits prouvés du niacinamide' },
      { type: 'ul', items: [
        '<strong>Régulation du sébum</strong> — réduit la production de sébum de 30 à 50% selon les études, idéal pour les peaux grasses et mixtes',
        '<strong>Réduction de l\'apparence des pores</strong> — en régulant le sébum, les pores paraissent moins dilatés',
        '<strong>Uniformisation du teint</strong> — inhibe le transfert de mélanine vers les cellules de surface, réduisant les taches et l\'hyperpigmentation',
        '<strong>Renforcement de la barrière cutanée</strong> — stimule la production de céramides, lipides essentiels à la barrière cutanée',
        '<strong>Effet anti-inflammatoire</strong> — réduit les rougeurs, apaise les peaux acnéiques et sensibles',
        '<strong>Action anti-âge</strong> — stimule la production de collagène et atténue les ridules superficielles',
      ]},
      { type: 'highlight', html: 'Le niacinamide est l\'un des seuls actifs qui convient à <strong>tous les types de peaux</strong> — sèche, grasse, mixte, sensible, mature. C\'est rare.' },
      { type: 'h2', text: 'Comment utiliser le niacinamide' },
      { type: 'p', html: 'La concentration optimale se situe entre <strong>5% et 10%</strong>. En dessous de 5%, les effets sont limités. Au-dessus de 10%, le risque d\'irritation augmente sans bénéfice supplémentaire prouvé.' },
      { type: 'ul', items: [
        'Appliquez matin et/ou soir, après le nettoyage et avant l\'hydratant',
        'Quelques gouttes suffisent — le niacinamide se répartit facilement',
        'Il peut être utilisé tous les jours, y compris sous le SPF le matin',
        'Commencez à une application par jour si vous avez une peau sensible',
      ]},
      { type: 'h2', text: 'Les meilleurs sérums à la niacinamide' },
      { type: 'product', name: 'The Ordinary Niacinamide 10% + Zinc 1%', description: 'Le rapport qualité-prix imbattable. 10% de niacinamide + zinc pour réguler le sébum et réduire les imperfections. La référence accessible.', price: '~6 €', link: 'https://www.amazon.fr/s?k=The+Ordinary+Niacinamide+10+Zinc+1&tag=ratemyskin-21' },
      { type: 'product', name: 'La Roche-Posay Toleriane Sérum Niacinamide', description: 'Formule dermatologiquement testée avec 10% de niacinamide pur. Plus chère mais idéale pour les peaux ultra-sensibles qui réagissent aux formules basiques.', price: '~22 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Toleriane+sérum+niacinamide&tag=ratemyskin-21' },
      { type: 'h2', text: 'Niacinamide et vitamine C : peut-on les mélanger ?' },
      { type: 'p', html: 'Longtemps, on a cru que mélanger niacinamide et vitamine C créait du niacine — une substance qui provoque des rougeurs. C\'est un mythe. Des études récentes montrent que cette réaction ne se produit pas dans les conditions d\'utilisation normale.' },
      { type: 'p', html: 'Cependant, la vitamine C pure (acide ascorbique) est une molécule instable qui s\'oxyde facilement. Pour maximiser leurs effets respectifs, l\'idéal est de les appliquer à des moments différents&nbsp;: vitamine C le matin (antioxydant contre les UV), niacinamide le soir. Mais les appliquer ensemble n\'est pas dangereux.' },
      { type: 'h2', text: 'Pour qui est fait le niacinamide ?' },
      { type: 'p', html: 'Pour (presque) tout le monde&nbsp;:' },
      { type: 'ul', items: [
        'Peau grasse → régule le sébum et réduit les pores',
        'Peau acnéique → anti-inflammatoire et réduit les marques post-acné',
        'Peau terne avec taches → uniformise le teint',
        'Peau sensible → renforce la barrière, bien toléré',
        'Peau mature → action anti-âge légère',
      ]},
      { type: 'p', html: 'Le seul cas où le niacinamide peut poser problème&nbsp;: une allergie à la niacine (vitamine B3) — extrêmement rare. Si vous avez une rougeur intense ou des picotements marqués à l\'application, c\'est peut-être votre cas. Faites toujours un patch test à l\'intérieur du poignet 24h avant d\'appliquer sur le visage.' },
      { type: 'p', html: 'Pour savoir si le niacinamide est l\'actif dont votre peau a besoin en priorité, une analyse <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> identifie vos problèmes cutanés spécifiques et vous recommande les actifs les plus pertinents. Voir aussi&nbsp;: <a href="/blog/acne-adulte-solutions" style="color:#A87449;">acné adulte</a>, <a href="/blog/routine-skincare-debutant" style="color:#A87449;">routine skincare débutant</a>.' },
      { type: 'cta' },
    ],
  },

  {
    slug: 'proteger-peau-soleil',
    title: 'Comment protéger sa peau du soleil (guide expert)',
    metaTitle: 'Protéger sa peau du soleil : guide SPF complet 2026 | Rate My Skin',
    metaDescription: 'Comment vraiment protéger sa peau du soleil ? SPF 30 ou 50, application, réapplication, meilleurs solaires visage. Tous les conseils essentiels.',
    keyword: 'protection solaire',
    excerpt: 'La protection solaire est l\'anti-âge le plus efficace qui existe. Et pourtant, la plupart d\'entre nous l\'appliquent mal. Guide complet sur le SPF.',
    readingTime: 6,
    publishedAt: '2026-05-15',
    category: 'Protection',
    content: [
      { type: 'p', html: 'Voici un chiffre qui devrait tout changer&nbsp;: <strong>80% du vieillissement visible du visage est causé par les UV</strong> — rides, taches, perte d\'éclat, peau flasque. C\'est ce que les chercheurs appellent le photo-vieillissement. Et la bonne nouvelle&nbsp;: c\'est en grande partie évitable avec un produit simple, peu cher, et disponible partout. La crème solaire.' },
      { type: 'p', html: 'Pourtant, la majorité des Français n\'appliquent du SPF qu\'en été, à la plage. C\'est insuffisant. Les UV traversent les nuages, les vitres de voiture, et agissent même par temps couvert. La protection solaire quotidienne est, sans exagérer, le geste anti-âge le plus efficace qui existe.' },
      { type: 'h2', text: 'UVA vs UVB : comprendre la différence' },
      { type: 'p', html: 'Le spectre solaire comporte deux types de rayonnements UV qui atteignent notre peau&nbsp;:' },
      { type: 'ul', items: [
        '<strong>UVB</strong> — responsables des coups de soleil, de la production de vitamine D, et des cancers de la peau. Leur intensité varie avec la saison et l\'heure.',
        '<strong>UVA</strong> — pénètrent plus profondément dans le derme. Responsables du vieillissement cutané et des taches. Leur intensité est quasi constante toute l\'année, toute la journée, même par temps nuageux.',
      ]},
      { type: 'p', html: 'Le chiffre SPF (ex&nbsp;: SPF 50) mesure uniquement la protection contre les UVB. Pour être protégé des UVA, cherchez un produit avec la mention "<strong>large spectre</strong>" ou le logo UVA dans un cercle — c\'est obligatoire sur les crèmes solaires conformes aux standards européens.' },
      { type: 'h2', text: 'Filtres minéraux vs filtres chimiques : lequel choisir ?' },
      { type: 'h3', text: 'Les filtres minéraux (physiques)' },
      { type: 'p', html: 'Oxyde de zinc et dioxyde de titane. Ils agissent comme un miroir&nbsp;: ils reflètent et dispersent les UV avant qu\'ils ne pénètrent dans la peau. Ils sont efficaces immédiatement à l\'application, bien tolérés sur les peaux sensibles et les peaux acnéiques. Inconvénient&nbsp;: texture parfois plus épaisse, effet "masque blanc" sur les peaux foncées (bien que les formulations modernes aient considérablement amélioré ce point).' },
      { type: 'h3', text: 'Les filtres chimiques (organiques)' },
      { type: 'p', html: 'Avobenzone, oxybenzone, tinosorb, mexoryl… Ils absorbent les UV et les convertissent en chaleur. Textures légères, invisibles sur tous les phototypes, souvent plus agréables à porter au quotidien. Certains peuvent être irritants sur les peaux très sensibles. Nécessitent 20 minutes d\'attente après application pour être pleinement actifs.' },
      { type: 'highlight', html: 'La plupart des <strong>crèmes solaires modernes</strong> combinent les deux types de filtres pour maximiser la protection et améliorer la texture. Choisissez selon votre type de peau, pas selon un idéalisme ingrédients.' },
      { type: 'h2', text: 'SPF 30 ou SPF 50 : quelle différence concrète ?' },
      { type: 'p', html: 'SPF 30 bloque environ 97% des UVB. SPF 50 en bloque environ 98%. La différence est faible — mais elle compte si vous avez une peau claire, un risque de cancer élevé ou si vous êtes exposé(e) longtemps. Pour un usage quotidien en ville, SPF 30 est généralement suffisant. Pour la plage, le sport outdoor ou les peaux très claires&nbsp;: SPF 50 minimum.' },
      { type: 'h2', text: 'Comment appliquer correctement sa protection solaire' },
      { type: 'p', html: 'L\'application est aussi importante que le produit lui-même. La plupart des gens appliquent 2 à 4 fois moins de crème solaire que la quantité nécessaire pour obtenir le SPF indiqué.' },
      { type: 'ul', items: [
        'Quantité recommandée pour le visage : une demi-cuillère à café (environ 1/4 cuillère à café si vous mettez aussi le cou)',
        'Appliquer 20 minutes avant l\'exposition (surtout pour les filtres chimiques)',
        'Renouveler toutes les 2 heures en cas d\'exposition prolongée, après la baignade ou la transpiration',
        'Couvrir le contour des yeux, le nez, les oreilles et le cou — zones souvent oubliées',
      ]},
      { type: 'h2', text: 'Les erreurs les plus fréquentes' },
      { type: 'ul', items: [
        'N\'appliquer le SPF qu\'en été (les UVA agissent toute l\'année)',
        'Compter sur le SPF dans le fond de teint ou le BB cream (quantité insuffisante)',
        'Ne pas renouveler l\'application en cas d\'exposition longue',
        'Oublier les zones sensibles (oreilles, cou, lèvres)',
        'Penser que les peaux foncées n\'ont pas besoin de SPF (faux — elles vieillissent aussi et peuvent développer des cancers)',
      ]},
      { type: 'product', name: 'La Roche-Posay Anthelios Invisible Fluid SPF 50+', description: 'Texture ultra-légère, résistante à la transpiration, sans traces blanches. La référence dermato pour un usage quotidien sur tous les phototypes.', price: '~15 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Anthelios+Invisible+Fluid&tag=ratemyskin-21' },
      { type: 'product', name: 'Avène SPF 50+ Solaire Hydratant', description: 'Idéal pour les peaux sensibles et réactives. Formule apaisante à l\'eau thermale d\'Avène, filtre large spectre, très bien tolérée.', price: '~12 €', link: 'https://www.amazon.fr/s?k=Avène+SPF+50+solaire&tag=ratemyskin-21' },
      { type: 'h2', text: 'Protection solaire et vitamine D : faut-il s\'inquiéter ?' },
      { type: 'p', html: 'Un mythe courant&nbsp;: "si je mets du SPF, je ne fais plus de vitamine D". En pratique, la plupart des gens n\'appliquent pas une quantité suffisante de crème solaire pour bloquer totalement la synthèse de vitamine D. Par ailleurs, la vitamine D peut être obtenue via l\'alimentation (poissons gras, œufs, champignons) ou la supplémentation. Ne jamais sacrifier la protection solaire pour la vitamine D — ce n\'est pas un arbitrage nécessaire.' },
      { type: 'p', html: 'Pour savoir si votre peau présente des dommages solaires existants (taches, hyperpigmentation, vieillissement prématuré), <a href="https://ratemyskin.co" style="color:#A87449;font-weight:600;">Rate My Skin</a> les détecte sur une simple photo. Consultez aussi nos guides&nbsp;: <a href="/blog/comment-connaitre-son-type-de-peau" style="color:#A87449;">connaître son type de peau</a> et <a href="/blog/routine-skincare-debutant" style="color:#A87449;">routine skincare débutant</a>.' },
      { type: 'cta' },
    ],
  },
  {
    slug: 'barriere-cutanee-abimee',
    title: 'Barrière cutanée abîmée : symptômes, causes et comment la réparer (2026)',
    metaTitle: 'Barrière cutanée abîmée : symptômes et solutions 2026 | Rate My Skin',
    metaDescription: 'Ta peau tire, rougit ou réagit à tout ? Ta barrière cutanée est probablement abîmée. Découvre comment la réparer avec les bons actifs et la bonne routine.',
    keyword: 'barrière cutanée abîmée',
    excerpt: 'Peau qui tire, rougeurs diffuses, boutons inexpliqués : et si ta barrière cutanée était abîmée ? Apprends à reconnaître les signes et à réparer ton film protecteur.',
    readingTime: 7,
    publishedAt: '2026-06-08',
    category: 'PROBLÈMES DE PEAU',
    content: [
      { type: 'p', html: 'Tu appliques ta crème hydratante habituelle, et soudain, ça pique. Ta peau tiraille en plein milieu de la journée, elle présente des rougeurs diffuses et réagit à la moindre goutte d\'eau. Le réflexe classique ? Acheter de nouveaux produits "apaisants" ou des exfoliants pour lisser le grain de peau. C\'est souvent la pire erreur. Si tu ressens ces symptômes, le problème ne vient pas d\'un manque de produits, mais d\'un bouclier invisible défaillant : ta <strong>barrière cutanée est abîmée</strong>.' },
      { type: 'h2', text: 'C\'est quoi la barrière cutanée ?' },
      { type: 'p', html: 'Imagine ta peau comme un mur de briques. Les cellules de la peau (les cornéocytes) sont les briques, et les lipides (céramides, cholestérol, acides gras) sont le ciment qui maintient tout ensemble. C\'est ce qu\'on appelle le film hydrolipidique.' },
      { type: 'p', html: 'Son rôle est double :<br>1. <strong>Garder l\'eau à l\'intérieur</strong> (empêcher la déshydratation).<br>2. <strong>Garder les agresseurs à l\'extérieur</strong> (bactéries, pollution, allergènes).' },
      { type: 'h2', text: 'Les signes évidents d\'une barrière cutanée abîmée' },
      { type: 'p', html: 'Comment savoir si ton "mur" est fissuré ? Arrête de deviner, voici les symptômes qui ne trompent pas :' },
      { type: 'ul', items: [
        'Tes produits habituels te brûlent ou te piquent à l\'application',
        'Ta peau tire et semble "cartonneuse", même après avoir mis de la crème',
        'L\'apparition soudaine de rougeurs, de plaques de sécheresse ou de desquamation',
        'Une production excessive de sébum accompagnée d\'un tiraillement (la peau surcompense)',
        'Des éruptions cutanées, des microkystes ou une aggravation soudaine de ton acné',
      ]},
      { type: 'highlight', html: '💡 <strong>Conseil :</strong> Si ta peau rougit ou chauffe quand tu la laves à l\'eau tiède, ta barrière est compromise. Cesse toute exfoliation immédiatement.' },
      { type: 'h2', text: 'Qu\'est-ce qui détruit ce bouclier ?' },
      { type: 'p', html: 'Souvent, nous sommes les propres bourreaux de notre peau. Les causes principales d\'une barrière cutanée abîmée sont liées à nos routines skincare trop agressives :' },
      { type: 'ul', items: [
        '<strong>Le sur-nettoyage :</strong> utiliser des gels nettoyants purifiants trop décapants ou se laver le visage 3 fois par jour.',
        '<strong>La sur-exfoliation :</strong> empiler les AHA, le BHA et les gommages à grains dans la même semaine.',
        '<strong>Le cocktail d\'actifs :</strong> mélanger rétinol, vitamine C et acides sans laisser à la peau le temps de s\'adapter.',
        '<strong>L\'environnement :</strong> le vent froid, le chauffage excessif, ou l\'eau très calcaire de la douche.',
      ]},
      { type: 'cta', kicker: 'ROUGEURS & DÉSHYDRATATION', title: 'Où en est ta barrière cutanée ?', desc: 'Découvre en 30 secondes si tes rougeurs ou ta peau qui tire sont le signe d\'une barrière abîmée grâce à notre scan IA.', buttonText: 'Analyser ma sensibilité →' },
      { type: 'h2', text: 'Comment réparer ta barrière cutanée (étape par étape)' },
      { type: 'p', html: 'La réparation d\'une barrière cutanée abîmée demande de la patience (compte 2 à 4 semaines de "diète skincare") et une routine minimaliste stricte. Voici le plan d\'action.' },
      { type: 'h3', text: '1. Revenir à la règle des 3 produits' },
      { type: 'p', html: 'Mets au placard TOUS tes actifs. Plus de vitamine C, plus d\'acides exfoliants, plus de rétinol. Ta routine doit se limiter à l\'essentiel : un nettoyant doux, une crème hydratante réparatrice, et un SPF. C\'est ce qu\'on appelle le skinimalisme.' },
      { type: 'h3', text: '2. Miser sur les ingrédients "pansement"' },
      { type: 'p', html: 'Pour réparer le ciment de ta peau, tu dois lui apporter ce dont elle est naturellement composée, ou ce qui l\'apaise :' },
      { type: 'ul', items: [
        '<strong>Les céramides :</strong> ce sont les lipides naturellement présents dans la peau. Ils colmatent les brèches.',
        '<strong>L\'acide hyaluronique et la glycérine :</strong> pour réhydrater en profondeur.',
        '<strong>Le panthenol (Vitamine B5) et l\'allantoïne :</strong> pour apaiser instantanément les rougeurs.',
        '<strong>Le niacinamide (à faible dose, < 5%) :</strong> il aide à relancer la production naturelle de céramides.',
      ]},
      { type: 'product', name: 'CeraVe Crème Hydratante Visage', description: 'Le parfait basique réparateur. Contient 3 céramides essentiels et de l\'acide hyaluronique pour restaurer la barrière cutanée en douceur.', price: '~14 €', link: 'https://www.amazon.fr/s?k=CeraVe+Crème+Hydratante+Visage&tag=ratemyskin-21' },
      { type: 'product', name: 'La Roche-Posay Cicaplast Baume B5+', description: 'Le "pansement" ultime pour les peaux très irritées. Idéal en application le soir sur les zones particulièrement sèches ou rouges.', price: '~12 €', link: 'https://www.amazon.fr/s?k=La+Roche+Posay+Cicaplast+Baume+B5&tag=ratemyskin-21' },
      { type: 'h2', text: 'Les erreurs à éviter pendant la guérison' },
      { type: 'p', html: 'La pire chose à faire est de s\'impatienter. N\'essaie pas de réintroduire tes exfoliants dès que les rougeurs disparaissent. Attends au moins 3 à 4 semaines de confort cutané total. Ne te lave jamais le visage à l\'eau chaude (l\'eau tiède, voire fraîche, est ton alliée), et évite les cotons démaquillants qui créent de la micro-friction.' },
      { type: 'h2', text: 'FAQ : Comprendre la barrière cutanée' },
      { type: 'h3', text: 'Combien de temps faut-il pour réparer une barrière cutanée abîmée ?' },
      { type: 'p', html: 'En général, il faut compter entre 2 et 4 semaines avec une routine très douce pour qu\'une peau jeune et en bonne santé se répare. Pour les dommages plus profonds ou les peaux matures, cela peut prendre jusqu\'à 8 semaines.' },
      { type: 'h3', text: 'Est-ce que l\'acné peut venir d\'une barrière abîmée ?' },
      { type: 'p', html: 'Absolument. Quand la barrière est endommagée, les bactéries pénètrent plus facilement, et la peau produit plus de sébum pour essayer de se protéger, créant le terrain idéal pour une éruption d\'acné inflammatoire.' },
      { type: 'p', html: 'Tu as un doute sur l\'état actuel de ton film protecteur ? Au lieu de tester au hasard des produits apaisants, vérifie les niveaux d\'hydratation et de rougeurs de ton visage. L\'IA de Rate My Skin cartographie ta peau pour te dire exactement ce dont tu as besoin.' },
      { type: 'cta', kicker: 'RÉPARE TA PEAU', title: 'Fais le point sur ta barrière cutanée', desc: 'Scan IA gratuit : découvre le score d\'hydratation et de rougeurs de ta peau, et obtiens la routine exacte pour la réparer.', buttonText: 'Lancer mon analyse 100% gratuite →' },
    ],
  },

  {
    slug: 'pores-dilates-points-noirs',
    title: 'Pores dilatés et points noirs : comment les réduire vraiment (2026)',
    metaTitle: 'Pores dilatés et points noirs : comment s\'en débarrasser | Rate My Skin',
    metaDescription: 'Marre des pores dilatés sur le nez et les joues ? Voici la routine et les actifs (BHA, Niacinamide) prouvés pour resserrer les pores et lisser ta peau.',
    keyword: 'pores dilatés',
    excerpt: 'Impossible de faire "disparaître" ses pores, mais tu peux diviser leur taille par deux avec les bons actifs. Finis les patchs arracheurs, place à la science.',
    readingTime: 6,
    publishedAt: '2026-06-08',
    category: 'PROBLÈMES DE PEAU',
    content: [
      { type: 'p', html: 'C\'est l\'obsession numéro 1 de beaucoup d\'entre nous : ces petits trous visibles sur le nez, le front ou les joues, souvent accompagnés de points noirs. On dépense des fortunes dans des "effaceurs de pores", des patchs arracheurs, ou des masques miracle... souvent pour rien. Pourquoi ? Parce qu\'on attaque le problème de la mauvaise façon. Comprendre <strong>pourquoi</strong> tes pores sont dilatés est la seule manière de les réduire durablement.' },
      { type: 'h2', text: 'Un pore dilaté, c\'est quoi exactement ?' },
      { type: 'p', html: 'Un pore n\'est pas un muscle. Il ne s\'ouvre et ne se ferme pas à l\'eau chaude ou froide. C\'est simplement l\'orifice par lequel s\'écoule le sébum produit par ta peau. Plus tes glandes sébacées produisent de gras, plus le canal doit s\'élargir pour laisser passer ce flux. Résultat : le pore se dilate.' },
      { type: 'p', html: 'Si ce sébum se mélange à des cellules mortes et s\'oxyde au contact de l\'air, il noircit. C\'est la naissance du fameux <strong>point noir</strong> (ou comédon ouvert).' },
      { type: 'h2', text: 'Les vraies causes des pores visibles' },
      { type: 'ul', items: [
        '<strong>La surproduction de sébum :</strong> la cause principale chez les peaux grasses et mixtes.',
        '<strong>L\'accumulation de cellules mortes :</strong> qui viennent "boucher" et étirer le pore.',
        '<strong>La perte de collagène :</strong> avec l\'âge ou les dommages liés au soleil (UV), la peau perd de son élasticité. Les pores s\'affaissent et paraissent plus grands.',
        '<strong>La génétique :</strong> l\'épaisseur de la peau et la taille des glandes sébacées sont en grande partie héréditaires.',
      ]},
      { type: 'highlight', html: '💡 <strong>Conseil :</strong> Ne confonds pas points noirs et filaments sébacés. Les petits points grisâtres sur ton nez sont souvent des filaments naturels. Les points noirs sont plus gros, plus foncés, et souvent en relief.' },
      { type: 'cta', kicker: 'TESTE TA PEAU', title: 'Quel est ton score de pores ?', desc: 'Notre IA cartographie la taille et la densité de tes pores pour te dire si ton problème vient du sébum ou du relâchement cutané.', buttonText: 'Analyser mes pores gratuitement →' },
      { type: 'h2', text: 'Quoi faire : la méthode en 3 étapes' },
      { type: 'p', html: 'Oublie les patchs purifiants qui arrachent la couche protectrice de ta peau. La stratégie gagnante repose sur le nettoyage profond et le renouvellement cellulaire.' },
      { type: 'h3', text: 'Étape 1 : Le double nettoyage le soir' },
      { type: 'p', html: 'Le gras dissout le gras. Le double nettoyage (utiliser une huile/baume démaquillant suivi d\'un gel nettoyant) est la méthode la plus efficace pour déloger le sébum et les filtres solaires qui encombrent les pores. C\'est le "game changer" absolu pour les peaux congestionnées.' },
      { type: 'h3', text: 'Étape 2 : L\'exfoliation chimique (Acide Salicylique / BHA)' },
      { type: 'p', html: 'L\'acide salicylique est liposoluble (soluble dans le gras). Contrairement aux gommages à grains qui ne grattent que la surface, le BHA pénètre <em>à l\'intérieur</em> du pore pour dissoudre le bouchon de sébum et de cellules mortes. Utilise-le 2 à 3 soirs par semaine.' },
      { type: 'product', name: 'Paula\'s Choice Skin Perfecting 2% BHA', description: 'L\'étalon-or pour resserrer les pores. Ce liquide exfoliant s\'applique comme une lotion et désincruste visiblement les points noirs en quelques semaines.', price: '~30 €', link: 'https://www.amazon.fr/s?k=Paula+Choice+2+BHA+Liquid&tag=ratemyskin-21' },
      { type: 'h3', text: 'Étape 3 : Le Niacinamide' },
      { type: 'p', html: 'C\'est l\'actif roi pour affiner le grain de peau. En régulant la production de sébum à la source, il empêche le pore de se dilater à nouveau une fois nettoyé. Il améliore aussi l\'élasticité des parois du pore.' },
      { type: 'product', name: 'The Ordinary Niacinamide 10% + Zinc 1%', description: 'Parfait pour contrôler la brillance et resserrer l\'apparence des pores. À appliquer le matin sous la crème hydratante.', price: '~6 €', link: 'https://www.amazon.fr/s?k=The+Ordinary+Niacinamide+10+Zinc+1&tag=ratemyskin-21' },
      { type: 'h2', text: 'Les erreurs à éviter absolument' },
      { type: 'p', html: 'Fuir les produits "astringents" à base d\'alcool pur. Sur le moment, ils donnent une sensation de peau ultra-propre et resserrée. En réalité, ils déshydratent la peau, ce qui la pousse à... produire encore plus de sébum pour se protéger. Cercle vicieux.' },
      { type: 'h2', text: 'FAQ : Pores et Points Noirs' },
      { type: 'h3', text: 'Peut-on refermer définitivement un pore dilaté ?' },
      { type: 'p', html: 'Non, c\'est anatomiquement impossible. Mais en le gardant propre (sans sébum oxydé à l\'intérieur) et en stimulant l\'élasticité de la peau, il devient presque invisible à l\'œil nu.' },
      { type: 'h3', text: 'Faut-il percer ses points noirs ?' },
      { type: 'p', html: 'Jamais avec les ongles. Cela traumatise le pore, l\'étire de façon permanente et risque de créer une cicatrice ou une infection. Utilise plutôt des actifs chimiques (BHA) ou consulte un dermatologue pour une extraction professionnelle.' },
      { type: 'p', html: 'Arrête de deviner ce qui obstrue tes pores. Un simple scan de ton visage peut t\'aider à ajuster ta routine : as-tu besoin d\'un exfoliant puissant ou d\'un régulateur de sébum doux ?' },
      { type: 'cta', kicker: 'RÉDUIS TES PORES', title: 'Découvre ta routine sur-mesure', desc: 'Prends un selfie : notre IA évalue la congestion de tes pores et te recommande la concentration exacte de BHA et de Niacinamide qu\'il te faut.', buttonText: 'Scanner mon visage gratuitement →' },
    ],
  },

  {
    slug: 'cernes-causes-solutions',
    title: 'Cernes : pourquoi tu en as et comment les atténuer',
    metaTitle: 'Cernes sous les yeux : causes et meilleures solutions | Rate My Skin',
    metaDescription: 'Marre des cernes foncés ou creux ? Découvre pourquoi les crèmes classiques ne marchent pas toujours, et les solutions réelles selon ton type de cerne.',
    keyword: 'cernes',
    excerpt: 'Vaseline, sachets de thé, crèmes miracles : tu as tout essayé et tes cernes sont toujours là ? C\'est normal, il existe 3 types de cernes et chacun demande une approche radicalement différente.',
    readingTime: 6,
    publishedAt: '2026-06-08',
    category: 'PROBLÈMES DE PEAU',
    content: [
      { type: 'p', html: 'C\'est la réflexion qu\'on déteste tous entendre : <em>"Tu as l\'air fatigué(e) aujourd\'hui"</em>. Les cernes sous les yeux sont la préoccupation esthétique numéro 1, tous âges confondus. Pourtant, c\'est aussi le domaine où l\'on gaspille le plus d\'argent. Pourquoi ? Parce qu\'on achète des crèmes "anti-cernes" génériques, alors qu\'il existe différents types de cernes qui ne se traitent pas du tout de la même manière.' },
      { type: 'h2', text: 'La peau du contour de l\'œil : une zone à haut risque' },
      { type: 'p', html: 'La peau du contour de l\'œil est 3 à 5 fois plus fine que celle du reste du visage. Elle contient très peu de glandes sébacées (donc elle se déshydrate vite) et elle est sollicitée par plus de 10 000 clignements d\'yeux par jour. C\'est pour cela qu\'elle marque si vite la fatigue, le vieillissement et la déshydratation.' },
      { type: 'h2', text: 'Quel est ton type de cerne ?' },
      { type: 'p', html: 'Arrête de deviner. Pince légèrement la peau de ton cerne et soulève-la. Observe ce qu\'il se passe :' },
      { type: 'h3', text: '1. Les cernes vasculaires (bleus/violets)' },
      { type: 'p', html: 'Si en soulevant la peau, la couleur bleue/violette reste "au fond" (ne vient pas avec la peau), c\'est un cerne vasculaire. La peau est si fine qu\'on voit le réseau sanguin au travers. Le manque de sommeil, l\'alcool, le tabac et une mauvaise circulation sanguine ralentissent le flux et rendent le sang plus foncé (stagnation).' },
      { type: 'h3', text: '2. Les cernes pigmentaires (bruns/marrons)' },
      { type: 'p', html: 'Si en soulevant la peau, la couleur marron suit le mouvement de la peau, c\'est une hyperpigmentation. Ce type de cerne est souvent d\'origine génétique et très commun chez les peaux mates à foncées. Il peut être aggravé par les frottements (se frotter les yeux à cause d\'allergies) et le soleil.' },
      { type: 'h3', text: '3. Les cernes creux (structurels)' },
      { type: 'p', html: 'Si la couleur disparaît quand tu lèves le menton face à la lumière, ce n\'est pas un problème de couleur, mais une ombre créée par un creux. Ce creux est dû à la perte de graisse sous-cutanée (qui s\'accentue avec l\'âge) ou à la forme naturelle de l\'os de ton visage.' },
      { type: 'cta', kicker: 'DÉTECTION IA', title: 'Quel type de cernes as-tu vraiment ?', desc: 'Notre scan analyse ton contour des yeux pour déterminer si tes cernes sont pigmentaires ou vasculaires, et t\'indique les actifs exacts pour les cibler.', buttonText: 'Analyser mes cernes gratuitement →' },
      { type: 'h2', text: 'Comment traiter chaque type de cerne' },
      { type: 'p', html: 'Maintenant que tu as identifié ton ennemi, voici les seules stratégies qui ont fait leurs preuves scientifiquement.' },
      { type: 'h3', text: 'Pour les cernes vasculaires (bleus)' },
      { type: 'ul', items: [
        '<strong>La caféine :</strong> c\'est un vasoconstricteur. Elle resserre les vaisseaux sanguins, réduisant la stagnation du sang.',
        '<strong>La vitamine C :</strong> elle épaissit légèrement la peau au fil du temps en stimulant le collagène, rendant les vaisseaux moins visibles.',
        '<strong>Le froid :</strong> les roll-ons en métal ou les cuillères au frigo fonctionnent vraiment (temporairement) pour décongestionner.',
      ]},
      { type: 'product', name: 'The Ordinary Caffeine Solution 5% + EGCG', description: 'Un sérum ultra-concentré en caféine et en antioxydants issus du thé vert. Redoutable contre les cernes bleus et les poches du matin.', price: '~8 €', link: 'https://www.amazon.fr/s?k=The+Ordinary+Caffeine+Solution&tag=ratemyskin-21' },
      { type: 'h3', text: 'Pour les cernes pigmentaires (bruns)' },
      { type: 'ul', items: [
        '<strong>Le rétinol (spécial yeux) :</strong> accélère le renouvellement cellulaire pour éliminer les cellules pigmentées.',
        '<strong>La vitamine C et la Niacinamide :</strong> bloquent la production de nouvelle mélanine.',
        '<strong>Le SPF :</strong> OBLIGATOIRE. Les UV aggravent considérablement les cernes pigmentaires. Utilise des lunettes de soleil ou un SPF minéral (qui pique moins les yeux).',
      ]},
      { type: 'h3', text: 'Pour les cernes creux' },
      { type: 'p', html: 'Il faut être honnête : <strong>aucune crème ne peut combler un trou</strong>. Si tu as des cernes structurels, l\'acide hyaluronique topique va seulement repulper la couche superficielle (c\'est bien, mais insuffisant). La seule vraie solution est la médecine esthétique (injections d\'acide hyaluronique ou lipofilling). En attendant, l\'astuce réside dans un correcteur (anti-cernes) bien lumineux appliqué uniquement au fond du creux.' },
      { type: 'h2', text: 'Les erreurs à éviter' },
      { type: 'p', html: 'N\'applique jamais ta crème anti-acné ou ton rétinol visage fort sur le contour des yeux. La peau y absorbe les produits beaucoup plus vite, ce qui provoque des brûlures, des rougeurs, et une sécheresse qui va... creuser tes cernes davantage.' },
      { type: 'h2', text: 'FAQ : Cernes et contour des yeux' },
      { type: 'h3', text: 'Faut-il vraiment une crème spéciale contour des yeux ?' },
      { type: 'p', html: 'Pas toujours. Si ta crème hydratante visage est basique (sans parfum, sans acides forts), tu peux l\'appliquer sous les yeux. Mais si tu veux traiter un problème spécifique (cernes bleus), un sérum contour des yeux concentré en caféine sera nécessaire.' },
      { type: 'h3', text: 'Est-ce que boire de l\'eau fait disparaître les cernes ?' },
      { type: 'p', html: 'La déshydratation creuse les traits et rend le sang plus sombre. Boire suffisamment est crucial, mais si tes cernes sont génétiques ou pigmentaires, l\'eau ne suffira pas à les effacer.' },
      { type: 'p', html: 'Tu hésites entre un sérum à la caféine ou à la vitamine C ? Ne choisis pas au hasard. L\'IA de Rate My Skin mesure l\'intensité et la nature de tes cernes pour te guider vers le bon choix.' },
      { type: 'cta', kicker: 'ÉCLAT DU REGARD', title: 'Analyse ton contour des yeux', desc: 'Scan IA gratuit : découvre le score de tes cernes et obtiens la recommandation de soin sur-mesure.', buttonText: 'Scanner mon visage gratuitement →' },
    ],
  },

  {
    slug: 'taches-hyperpigmentation',
    title: 'Taches et hyperpigmentation : le guide pour un teint uniforme',
    metaTitle: 'Taches brunes et hyperpigmentation : causes et traitements | Rate My Skin',
    metaDescription: 'Taches de soleil, masque de grossesse ou cicatrices d\'acné ? Apprends à traiter l\'hyperpigmentation avec la Vitamine C, l\'Acide Azélaïque et le SPF.',
    keyword: 'taches pigmentaires visage',
    excerpt: 'Les taches brunes ne sont pas une fatalité liée à l\'âge. Qu\'elles viennent du soleil, des hormones ou d\'un ancien bouton, voici le plan d\'attaque pour unifier ton teint.',
    readingTime: 7,
    publishedAt: '2026-06-08',
    category: 'PROBLÈMES DE PEAU',
    content: [
      { type: 'p', html: 'Ton acné a disparu, mais elle a laissé un "souvenir" sombre sur ta joue. Ou peut-être as-tu remarqué l\'apparition de taches marbrées sur ton front après tes dernières vacances. L\'hyperpigmentation est incroyablement frustrante car elle met des jours à apparaître, et des mois à disparaître. Mais avec la bonne combinaison d\'actifs, il est tout à fait possible de retrouver un teint uniforme.' },
      { type: 'h2', text: 'Pourquoi la peau fait-elle des taches ?' },
      { type: 'p', html: 'L\'hyperpigmentation survient quand les mélanocytes (les cellules qui donnent sa couleur à la peau) s\'emballent et produisent trop de mélanine sur une zone concentrée. Ce "bug" de surproduction a trois causes principales :' },
      { type: 'ul', items: [
        '<strong>1. L\'Hyperpigmentation Post-Inflammatoire (PIH) :</strong> C\'est la tache plate, rouge ou brune, qui reste après un bouton, une éraflure ou une piqûre. La peau a produit de la mélanine en réponse au traumatisme.',
        '<strong>2. Le Lentigo (taches de soleil / de vieillesse) :</strong> Des petites taches brunes bien définies dues à des années d\'exposition aux UV sans protection.',
        '<strong>3. Le Mélasma (masque de grossesse) :</strong> Des plaques brunes symétriques (souvent front, lèvre supérieure, joues) déclenchées par une combinaison d\'hormones (pilule, grossesse) et d\'exposition solaire.',
      ]},
      { type: 'h2', text: 'La règle d\'or : on ne traite pas sans protéger' },
      { type: 'p', html: 'Acheter un sérum anti-taches à 50€ et ne pas mettre de crème solaire, c\'est comme essayer de vider l\'océan avec une cuillère trouée. <strong>Les UV stimulent la production de mélanine</strong>. Même par temps nuageux, les rayons UVA pénètrent et foncent tes taches existantes. L\'étape numéro 1 du traitement de l\'hyperpigmentation est l\'application stricte d\'un SPF 50 tous les matins.' },
      { type: 'cta', kicker: 'DÉTECTION DE TACHES', title: 'Où en est ton uniformité de teint ?', desc: 'Notre IA scanne ton visage pour évaluer la densité et le contraste de tes taches pigmentaires, et te propose une routine ciblée.', buttonText: 'Analyser mes taches gratuitement →' },
      { type: 'h2', text: 'Les 4 actifs redoutables contre les taches' },
      { type: 'p', html: 'Pour vaincre les taches, il faut agir sur plusieurs fronts : bloquer la nouvelle production de mélanine, empêcher son transfert vers la surface, et accélérer l\'élimination des cellules déjà tachées.' },
      { type: 'h3', text: '1. La Vitamine C (L\'antioxydant)' },
      { type: 'p', html: 'Elle bloque l\'enzyme (tyrosinase) responsable de la création de mélanine. Elle s\'applique le matin, sous le SPF, pour booster la protection solaire et illuminer le teint global.' },
      { type: 'h3', text: '2. L\'Acide Azélaïque (Le sous-estimé)' },
      { type: 'p', html: 'Un actif exceptionnel, particulièrement efficace sur l\'hyperpigmentation post-inflammatoire et le mélasma. Bonus : il est antibactérien, donc il traite l\'acné tout en effaçant les traces des anciens boutons. Sûr, même pendant la grossesse.' },
      { type: 'product', name: 'Paula\'s Choice 10% Azelaic Acid Booster', description: 'Une formule puissante qui combine de l\'acide azélaïque et de l\'acide salicylique pour cibler les taches rebelles et affiner le grain de peau.', price: '~39 €', link: 'https://www.amazon.fr/s?k=Paula+Choice+Azelaic+Acid&tag=ratemyskin-21' },
      { type: 'h3', text: '3. L\'Acide Tranexamique (Le bouclier mélasma)' },
      { type: 'p', html: 'Moins connu, cet actif est redoutable pour empêcher les mélanocytes de s\'activer après une exposition aux UV ou un pic hormonal.' },
      { type: 'h3', text: '4. Les AHA / Rétinoides (L\'accélérateur)' },
      { type: 'p', html: 'L\'Acide Glycolique ou le Rétinol ne bloquent pas la production de mélanine, mais ils forcent la peau à se renouveler plus vite, faisant ainsi "remonter" et peler les cellules tachées plus rapidement.' },
      { type: 'highlight', html: '💡 <strong>Conseil :</strong> Associer un ingrédient qui <em>bloque</em> la mélanine (Vitamine C / Acide Azélaïque) avec un ingrédient qui <em>renouvelle</em> la peau (Rétinol / AHA) est la combinaison la plus puissante.' },
      { type: 'h2', text: 'FAQ : Traitement des taches' },
      { type: 'h3', text: 'Combien de temps faut-il pour voir un résultat ?' },
      { type: 'p', html: 'La patience est cruciale. Le renouvellement complet de la peau prend environ 28 jours, et il s\'allonge avec l\'âge. Il faut compter au moins <strong>8 à 12 semaines</strong> de routine assidue pour voir une vraie différence sur une tache brune.' },
      { type: 'h3', text: 'Est-ce que le jus de citron marche sur les taches ?' },
      { type: 'p', html: 'Surtout pas ! Le citron est hautement phototoxique. Appliqué sur la peau et exposé au soleil, il provoque des brûlures chimiques graves qui vont... créer des taches sombres permanentes (phytophotodermatose).' },
      { type: 'p', html: 'Tu ne sais pas par quel actif commencer ? Vitamine C, Niacinamide, Acide Azélaïque ? Au lieu d\'empiler les produits au hasard, fais un état des lieux. L\'IA de Rate My Skin évalue l\'étendue de ton hyperpigmentation et te construit une routine sur-mesure.' },
      { type: 'cta', kicker: 'TEINT UNIFORME', title: 'Découvre ta routine anti-taches', desc: 'Scan IA gratuit : obtiens le score de tes taches et la combinaison d\'actifs exacte dont ta peau a besoin.', buttonText: 'Lancer mon analyse gratuite →' },
    ],
  },

  {
    slug: 'peau-terne-eclat',
    title: 'Peau terne : retrouver de l\'éclat naturellement',
    metaTitle: 'Peau terne et fatiguée : causes et solutions pour retrouver de l\'éclat | Rate My Skin',
    metaDescription: 'Ton teint est grisâtre et manque de lumière ? Découvre les vraies causes de la peau terne (cellules mortes, déshydratation) et comment raviver ton éclat.',
    keyword: 'peau terne',
    excerpt: 'Teint brouillé, mine fatiguée, peau qui manque de lumière : la peau terne est le premier signe d\'une peau qui ne respire plus. Voici comment retrouver le fameux "glow" sans maquillage.',
    readingTime: 5,
    publishedAt: '2026-06-08',
    category: 'PROBLÈMES DE PEAU',
    content: [
      { type: 'p', html: 'On connaît tous ce matin où, face au miroir, on a l\'impression d\'avoir pris 5 ans dans la nuit. Le teint est gris, brouillé, la peau manque de lumière et de rebond. On appelle ça une peau terne. Ce n\'est pas un "type" de peau, mais un état passager. Et la bonne nouvelle, c\'est que c\'est l\'un des problèmes cutanés les plus rapides et les plus faciles à résoudre quand on s\'y prend bien.' },
      { type: 'h2', text: 'Pourquoi ta peau perd-elle son éclat ?' },
      { type: 'p', html: 'La lumière se reflète mal sur une surface rugueuse ou sèche. C\'est exactement ce qu\'il se passe sur ton visage. Les 3 causes principales sont :' },
      { type: 'ul', items: [
        '<strong>1. L\'accumulation de cellules mortes :</strong> La peau se renouvelle naturellement tous les 28 jours, mais avec l\'âge, la fatigue ou le stress, ce processus ralentit. Les cellules mortes s\'empilent en surface, absorbant la lumière au lieu de la refléter.',
        '<strong>2. La déshydratation :</strong> Comme un raisin sec comparé à un raisin frais, une peau qui manque d\'eau (et non de gras) est visuellement terne et "fripée".',
        '<strong>3. Le stress oxydatif (pollution, tabac, UV) :</strong> Ces facteurs créent des radicaux libres qui endommagent les cellules et ralentissent la microcirculation. Le sang afflue moins bien, donnant ce fameux "teint gris".',
      ]},
      { type: 'cta', kicker: 'MESURE TON GLOW', title: 'Quel est ton score d\'éclat ?', desc: 'Notre IA analyse la capacité de ta peau à refléter la lumière et identifie si ton teint terne vient d\'un manque d\'hydratation ou d\'un besoin d\'exfoliation.', buttonText: 'Analyser mon éclat gratuitement →' },
      { type: 'h2', text: 'Le plan d\'action anti-grise mine' },
      { type: 'h3', text: 'Étape 1 : L\'exfoliation chimique (AHA)' },
      { type: 'p', html: 'C\'est l\'étape miracle pour l\'éclat. Les Acides Alpha-Hydroxylés (comme l\'Acide Glycolique ou l\'Acide Lactique) dissolvent la "colle" qui maintient les cellules mortes à la surface de la peau. En une seule nuit, la peau retrouve un aspect lisse et lumineux.' },
      { type: 'product', name: 'The Ordinary Acide Glycolique 7% Solution Tonifiante', description: 'Une lotion exfoliante culte. À appliquer avec un coton le soir, 2 à 3 fois par semaine, pour un coup d\'éclat massif.', price: '~13 €', link: 'https://www.amazon.fr/s?k=The+Ordinary+Glycolic+Acid&tag=ratemyskin-21' },
      { type: 'h3', text: 'Étape 2 : L\'hydratation profonde' },
      { type: 'p', html: 'Une peau repulpée reflète la lumière. Intègre un sérum à l\'Acide Hyaluronique (à appliquer <em>toujours</em> sur peau légèrement humide) avant ta crème.' },
      { type: 'h3', text: 'Étape 3 : La protection antioxydante (Vitamine C)' },
      { type: 'p', html: 'Si l\'exfoliation révèle l\'éclat, la Vitamine C le protège. Elle neutralise les radicaux libres responsables du teint brouillé et donne un aspect "frais" instantané.' },
      { type: 'h2', text: 'L\'erreur à ne pas commettre' },
      { type: 'p', html: 'Penser que "plus on frotte, plus ça brille". Utiliser des gommages à gros grains (sucre, noyaux d\'abricots) crée des micro-déchirures. La peau, agressée, s\'épaissit pour se défendre, devenant... encore plus terne.' },
      { type: 'p', html: 'Tu veux raviver ton teint mais tu as peur de mal doser l\'exfoliation ? Ne devine pas. Prends un selfie et laisse Rate My Skin analyser tes besoins réels en 30 secondes.' },
      { type: 'cta', kicker: 'OBJECTIF GLOW', title: 'Découvre ta routine Éclat', desc: 'Un scan gratuit pour savoir exactement quels actifs utiliser (et à quelle fréquence) pour retrouver un teint lumineux.', buttonText: 'Lancer mon analyse 100% gratuite →' },
    ],
  },

  {
    slug: 'routine-minimaliste-skinimalisme',
    title: 'Routine minimaliste : la skincare efficace en moins de produits (skinimalisme)',
    metaTitle: 'Skinimalisme : la routine skincare minimaliste et efficace | Rate My Skin',
    metaDescription: 'Marre des routines en 10 étapes ? Découvre le skinimalisme : comment avoir une plus belle peau en utilisant moins de produits et en ciblant tes vrais besoins.',
    keyword: 'routine minimaliste',
    excerpt: 'L\'ère des routines en 10 étapes est révolue. Place au "skinimalisme". Moins de produits, moins de budget, mais plus de résultats. Voici comment construire une routine minimaliste redoutable.',
    readingTime: 6,
    publishedAt: '2026-06-08',
    category: 'ROUTINE',
    content: [
      { type: 'p', html: 'Double sérum, essence, tonique, huile, crème de nuit, contour des yeux... Les réseaux sociaux nous ont fait croire que pour avoir une belle peau, il fallait un diplôme en chimie et une salle de bain remplie de flacons. La réalité dermatologique est bien différente : empiler trop de cosmétiques est la cause numéro 1 des barrières cutanées abîmées et de l\'acné cosmétique. Bienvenue dans l\'ère du <strong>skinimalisme</strong> (la contraction de skin et minimalisme).' },
      { type: 'h2', text: 'Pourquoi moins c\'est (souvent) mieux' },
      { type: 'p', html: 'Notre peau a une capacité d\'absorption limitée. Au-delà de 3 ou 4 couches, les produits ne pénètrent plus, ils restent en surface, s\'oxydent, bouchent les pores et créent un "bouillon de culture" pour les bactéries. De plus, multiplier les produits, c\'est multiplier les conservateurs et les parfums, augmentant drastiquement le risque d\'allergie.' },
      { type: 'p', html: 'Le skinimalisme repose sur un principe simple : <strong>chaque produit doit avoir une utilité vitale ou cibler un problème précis</strong>.' },
      { type: 'h2', text: 'La routine minimaliste universelle (3 étapes)' },
      { type: 'p', html: 'Si on enlève tout le superflu, voici ce dont ta peau a biologiquement besoin :' },
      { type: 'h3', text: 'Le Matin : Protéger' },
      { type: 'ul', items: [
        '<strong>1. Rinçage (Optionnel) :</strong> Si tu as nettoyé ta peau le soir, un simple splash d\'eau tiède suffit souvent le matin.',
        '<strong>2. Hydratant léger :</strong> Pour maintenir le confort de la peau.',
        '<strong>3. SPF 50 :</strong> L\'étape non-négociable. Il remplace souvent la crème hydratante pour les peaux mixtes à grasses.',
      ]},
      { type: 'h3', text: 'Le Soir : Nettoyer et Réparer' },
      { type: 'ul', items: [
        '<strong>1. Nettoyant doux :</strong> Pour enlever le SPF, la pollution et le maquillage.',
        '<strong>2. Traitement ciblé (1 seul !) :</strong> Un sérum ou un actif choisi spécifiquement pour TON problème principal (ex: Acide Salicylique pour les boutons, ou Rétinol pour l\'anti-âge).',
        '<strong>3. Crème hydratante :</strong> Pour sceller l\'hydratation pendant la nuit.',
      ]},
      { type: 'product', name: 'CeraVe Hydrating Cleanser', description: 'Le nettoyant minimaliste par excellence. Il nettoie sans jamais agresser, adapté à tous les types de peau.', price: '~10 €', link: 'https://www.amazon.fr/s?k=CeraVe+Hydrating+Cleanser&tag=ratemyskin-21' },
      { type: 'cta', kicker: 'TES VRAIS BESOINS', title: 'Quel est LE produit qu\'il te manque ?', desc: 'Au lieu d\'acheter 5 sérums, découvre celui qui aura le plus d\'impact. Notre scan IA détermine ton besoin numéro 1 en 30 secondes.', buttonText: 'Découvrir ma priorité skincare →' },
      { type: 'h2', text: 'Comment passer au skinimalisme sans paniquer ?' },
      { type: 'p', html: 'La transition peut faire peur quand on a l\'habitude de sa routine en 8 étapes. L\'astuce est de faire un "reset". Retire tous tes actifs (acides, vitamine C, sérums) pendant 2 semaines. Garde juste le nettoyant, la crème et le SPF. Observe ta peau : est-elle plus calme ? Moins rouge ?' },
      { type: 'p', html: 'Ensuite, réintroduis <strong>un seul actif</strong>, celui qui répond à ton problème le plus urgent.' },
      { type: 'h2', text: 'Les produits qu\'on peut éliminer (sans regret)' },
      { type: 'ul', items: [
        '<strong>Les crèmes contour des yeux basiques :</strong> Si ta crème hydratante visage est douce et sans parfum, elle fait exactement le même travail.',
        '<strong>Les toniques astringents :</strong> Les nettoyants modernes ont déjà le bon pH, le tonique n\'est plus obligatoire pour rééquilibrer la peau.',
        '<strong>Les masques peel-off :</strong> Souvent agressifs et sans réel bénéfice long-terme.',
      ]},
      { type: 'p', html: 'La clé du skinimalisme, c\'est de <strong>comprendre sa peau</strong> pour arrêter d\'acheter au hasard. Si tu ne connais pas les besoins profonds de ton visage, tu continueras à accumuler des produits inutiles. Fais le tri : laisse l\'IA de Rate My Skin analyser tes métriques (hydratation, acné, taches, pores) et te donner LA routine minimaliste exacte qu\'il te faut.' },
      { type: 'cta', kicker: 'SKINIMALISME', title: 'Génère ta routine minimaliste', desc: 'Scan IA gratuit : on analyse tes 8 métriques de peau et on te crée une routine ultra-courte (3 à 4 produits max) 100% ciblée.', buttonText: 'Générer ma routine minimaliste →' },
    ],
  }
];

export function getArticleBySlug(slug) {
  return articles.find(a => a.slug === slug) || null;
}
