// Static catalog of 25 premium skincare products for Rate My Skin
// Distributed across categories: Nettoyants & Démaquillants, Toniques & Lotions, Sérums & Actifs, Crèmes & Hydratants, Protections SPF, Masques & Soins, Contour des yeux

export const STATIC_PRODUCTS = [
  // ── CATEGORY: CLEANSER (Nettoyants & Démaquillants) ──
  {
    id: 'prod-cerave-hydrating-cleanser',
    productName: 'CeraVe Hydrating Cleanser',
    brand: 'CeraVe',
    name: 'Hydrating Cleanser',
    description_fr: 'Nettoie en douceur, hydrate et aide à restaurer la barrière protectrice de la peau sans la tirailler.',
    description_en: 'Gently cleanses, hydrates, and helps restore the protective skin barrier without leaving a tight feeling.',
    price: '12€ - 16€',
    price_range: '€12–16',
    imageUrl: 'https://images.unsplash.com/photo-1556229010-aa3f7ff66b24?q=80&w=240&auto=format&fit=crop',
    concerns: ['dryness', 'redness'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    routineStep: 'cleanser',
    actives: ['Céramides', 'Acide Hyaluronique'],
    actives_en: ['Ceramides', 'Hyaluronic Acid'],
    rating: 4.8,
    count: '32k+',
    efficacyLabel_fr: '96% barrière cutanée préservée',
    efficacyLabel_en: '96% skin barrier preserved',
    amazonLink: 'https://www.amazon.fr/dp/B07C5K7VCR?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/nettoyant-hydratant-visage-et-corps-P3575001.html'
  },
  {
    id: 'prod-laroche-effaclar-gel',
    productName: 'La Roche-Posay Effaclar Gel',
    brand: 'La Roche-Posay',
    name: 'Effaclar Purifying Foaming Gel',
    description_fr: 'Nettoie en douceur les peaux grasses et sensibles, élimine les impuretés et l\'excès de sébum.',
    description_en: 'Gently cleanses oily and sensitive skin, removing impurities and excess sebum.',
    price: '13€ - 17€',
    price_range: '€13–17',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=240&auto=format&fit=crop',
    concerns: ['acne', 'pores'],
    skinTypes: ['oily', 'combination', 'sensitive'],
    routineStep: 'cleanser',
    actives: ['Zinc PCA', 'Eau Thermale'],
    actives_en: ['Zinc PCA', 'Thermal Spring Water'],
    rating: 4.7,
    count: '18k+',
    efficacyLabel_fr: '92% réduction du sébum visible',
    efficacyLabel_en: '92% visible sebum reduction',
    amazonLink: 'https://www.amazon.fr/dp/B004RDG7N2?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/effaclar---gel-moussant-purifiant-peaux-grasses-et-sensibles-P1377.html'
  },
  {
    id: 'prod-bioderma-crealine-h2o',
    productName: 'Bioderma Créaline H2O',
    brand: 'Bioderma',
    name: 'Créaline H2O Micellar Water',
    description_fr: 'L\'eau micellaire de référence qui nettoie, démaquille et apaise les peaux les plus sensibles.',
    description_en: 'The benchmark micellar water that cleanses, removes makeup, and soothes the most sensitive skin.',
    price: '10€ - 14€',
    price_range: '€10–14',
    imageUrl: 'https://images.unsplash.com/photo-1556229010-aa3f7ff66b24?q=80&w=240&auto=format&fit=crop',
    concerns: ['redness', 'redness'],
    skinTypes: ['sensitive', 'dry', 'normal', 'combination', 'oily'],
    routineStep: 'cleanser',
    actives: ['Micelles active', 'Extrait de Concombre'],
    actives_en: ['Active Micelles', 'Cucumber Extract'],
    rating: 4.9,
    count: '42k+',
    efficacyLabel_fr: '99% des impuretés éliminées',
    efficacyLabel_en: '99% of impurities removed',
    amazonLink: 'https://www.amazon.fr/dp/B002K88FOK?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/crealine-h2o---solution-micellaire-demaquillante-peaux-sensibles-P2616016.html'
  },
  {
    id: 'prod-cerave-sa-cleanser',
    productName: 'CeraVe SA Smoothing Cleanser',
    brand: 'CeraVe',
    name: 'SA Smoothing Cleanser',
    description_fr: 'Exfolie en douceur grâce à l\'acide salicylique pour lisser le grain de peau rugueux sans l\'irriter.',
    description_en: 'Gently exfoliates with salicylic acid to smooth rough skin texture without irritation.',
    price: '11€ - 15€',
    price_range: '€11–15',
    imageUrl: 'https://images.unsplash.com/photo-1556229010-aa3f7ff66b24?q=80&w=240&auto=format&fit=crop',
    concerns: ['acne', 'texture', 'pores'],
    skinTypes: ['oily', 'combination', 'normal'],
    routineStep: 'cleanser',
    actives: ['Acide Salicylique', 'Céramides', 'Acide Hyaluronique'],
    actives_en: ['Salicylic Acid', 'Ceramides', 'Hyaluronic Acid'],
    rating: 4.8,
    count: '24k+',
    efficacyLabel_fr: '94% pores désincrustés',
    efficacyLabel_en: '94% pores unclogged',
    amazonLink: 'https://www.amazon.fr/dp/B00U1YCGVQ?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/cerave-sa-smoothing-cleanser'
  },
  {
    id: 'prod-ordinary-squalane-cleanser',
    productName: 'The Ordinary Squalane Cleanser',
    brand: 'The Ordinary',
    name: 'Squalane Cleanser',
    description_fr: 'Un nettoyant doux qui démaquille et nettoie la peau tout en préservant son hydratation.',
    description_en: 'A gentle cleansing product formulated to target makeup removal while leaving skin feeling soft.',
    price: '10€ - 15€',
    price_range: '€10–15',
    imageUrl: 'https://images.unsplash.com/photo-1556229010-aa3f7ff66b24?q=80&w=240&auto=format&fit=crop',
    concerns: ['dryness', 'redness'],
    skinTypes: ['dry', 'normal', 'sensitive', 'combination'],
    routineStep: 'cleanser',
    actives: ['Squalane', 'Esters Lipophiles'],
    actives_en: ['Squalane', 'Lipophilic Esters'],
    rating: 4.6,
    count: '15k+',
    efficacyLabel_fr: '91% peau douce et hydratée',
    efficacyLabel_en: '91% soft and hydrated skin',
    amazonLink: 'https://www.amazon.fr/dp/B07V7934DT?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/squalane-cleanser---nettoyant-visage-demaquillant-P3848037.html'
  },

  // ── CATEGORY: TONER (Toniques & Hydratation) ──
  {
    id: 'prod-ordinary-glycolic-toner',
    productName: 'The Ordinary Glycolic Acid 7% Toning Solution',
    brand: 'The Ordinary',
    name: 'Glycolic Acid 7% Toning Solution',
    description_fr: 'Exfolie légèrement la surface de la peau pour raviver l\'éclat et améliorer visiblement la texture.',
    description_en: 'Gently exfoliates the skin surface to restore radiance and visibly improve texture.',
    price: '13€ - 16€',
    price_range: '€13–16',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=240&auto=format&fit=crop',
    concerns: ['texture', 'radiance', 'pores'],
    skinTypes: ['normal', 'combination', 'oily'],
    routineStep: 'toner',
    actives: ['Acide Glycolique 7%', 'Aloe Vera', 'Ginseng'],
    actives_en: ['Glycolic Acid 7%', 'Aloe Vera', 'Ginseng'],
    rating: 4.6,
    count: '21k+',
    efficacyLabel_fr: '89% teint plus uniforme',
    efficacyLabel_en: '89% more even skin tone',
    amazonLink: 'https://www.amazon.fr/dp/B071HBBK5S?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/glycolic-acid-7pct-toning-solution---lotion-tonique-exfoliante-P3224017.html'
  },
  {
    id: 'prod-paulas-choice-2-bha',
    productName: "Paula's Choice 2% BHA Liquid Exfoliant",
    brand: "Paula's Choice",
    name: 'Skin Perfecting 2% BHA Liquid Exfoliant',
    description_fr: 'Lotion exfoliante culte à l\'acide salicylique qui élimine les points noirs et resserre les pores.',
    description_en: 'Cult salicylic acid liquid exfoliant that clears blackheads, unclogs pores, and refines texture.',
    price: '34€ - 39€',
    price_range: '€34–39',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=240&auto=format&fit=crop',
    concerns: ['acne', 'pores', 'texture'],
    skinTypes: ['oily', 'combination', 'normal'],
    routineStep: 'toner',
    actives: ['Acide Salicylique 2%', 'Thé Vert'],
    actives_en: ['Salicylic Acid 2%', 'Green Tea Extract'],
    rating: 4.8,
    count: '28k+',
    efficacyLabel_fr: '96% réduction des comédons',
    efficacyLabel_en: '96% blackhead reduction',
    amazonLink: 'https://www.amazon.fr/dp/B00949CTQQ?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/paulas-choice-skin-perfecting-2-bha-liquid-exfoliant'
  },
  {
    id: 'prod-thayers-witch-hazel',
    productName: 'Thayers Witch Hazel Toner',
    brand: 'Thayers',
    name: 'Witch Hazel Lavender Toner',
    description_fr: 'Tonique naturel apaisant sans alcool qui resserre les pores et équilibre le pH de la peau.',
    description_en: 'Soothing alcohol-free natural toner that refines pores and balances skin pH.',
    price: '12€ - 16€',
    price_range: '€12–16',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=240&auto=format&fit=crop',
    concerns: ['redness', 'pores'],
    skinTypes: ['normal', 'dry', 'sensitive', 'combination'],
    routineStep: 'toner',
    actives: ['Hamamélis', 'Aloe Vera'],
    actives_en: ['Witch Hazel', 'Aloe Vera'],
    rating: 4.7,
    count: '16k+',
    efficacyLabel_fr: '93% peau apaisée et fraîche',
    efficacyLabel_en: '93% calmed and fresh skin',
    amazonLink: 'https://www.amazon.fr/dp/B00016XJBY?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/thayers-alcohol-free-witch-hazel-toner-lavender'
  },

  // ── CATEGORY: SERUM (Sérums & Actifs) ──
  {
    id: 'prod-ordinary-niacinamide',
    productName: 'The Ordinary Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    name: 'Niacinamide 10% + Zinc 1%',
    description_fr: 'Régule la production de sébum, resserre visiblement les pores et atténue les imperfections.',
    description_en: 'Regulates sebum production, visibly minimizes pores, and targets blemishes.',
    price: '7€ - 9€',
    price_range: '€7–9',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=240&auto=format&fit=crop',
    concerns: ['pores', 'acne', 'texture'],
    skinTypes: ['oily', 'combination', 'normal'],
    routineStep: 'serum',
    actives: ['Niacinamide 10%', 'Zinc PCA 1%'],
    actives_en: ['Niacinamide 10%', 'Zinc PCA 1%'],
    rating: 4.6,
    count: '45k+',
    efficacyLabel_fr: '91% sébum régulé et pores affinés',
    efficacyLabel_en: '91% regulated sebum & refined pores',
    amazonLink: 'https://www.amazon.fr/dp/B07PG5VDF4?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/the-ordinary-niacinamide-10-zinc-1'
  },
  {
    id: 'prod-ordinary-hyaluronic',
    productName: 'The Ordinary Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    name: 'Hyaluronic Acid 2% + B5',
    description_fr: 'Une formule d\'hydratation intense qui repulpe instantanément la peau en ciblant plusieurs couches.',
    description_en: 'An intense hydration formula that instantly plumps skin by targeting multiple depths.',
    price: '9€ - 12€',
    price_range: '€9–12',
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=240&auto=format&fit=crop',
    concerns: ['dryness', 'aging'],
    skinTypes: ['dry', 'normal', 'combination', 'sensitive', 'oily'],
    routineStep: 'serum',
    actives: ['Acide Hyaluronique', 'Vitamine B5'],
    actives_en: ['Hyaluronic Acid', 'Vitamin B5'],
    rating: 4.7,
    count: '26k+',
    efficacyLabel_fr: '94% peau repulpée et hydratée',
    efficacyLabel_en: '94% plumped and hydrated skin',
    amazonLink: 'https://www.amazon.fr/dp/B01MXV547V?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/acide-hyaluronique-2pct---b5---serum-hydratant-P3848035.html'
  },
  {
    id: 'prod-skinceuticals-ce-ferulic',
    productName: 'SkinCeuticals C E Ferulic',
    brand: 'SkinCeuticals',
    name: 'C E Ferulic Antioxidant Serum',
    description_fr: 'Sérum antioxydant haute efficacité à la vitamine C pure pour illuminer et raffermir la peau.',
    description_en: 'High-efficacy pure vitamin C antioxidant serum to brighten and firm skin.',
    price: '155€ - 185€',
    price_range: '€155–185',
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=240&auto=format&fit=crop',
    concerns: ['radiance', 'aging', 'dark_spots'],
    skinTypes: ['dry', 'normal', 'combination', 'sensitive'],
    routineStep: 'serum',
    actives: ['Vitamine C 15%', 'Vitamine E', 'Acide Férulique'],
    actives_en: ['Vitamin C 15%', 'Vitamin E', 'Ferulic Acid'],
    rating: 4.9,
    count: '6k+',
    efficacyLabel_fr: '98% éclat et fermeté améliorés',
    efficacyLabel_en: '98% improved radiance and firmness',
    amazonLink: 'https://www.amazon.fr/dp/B000FGDQAS?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/skinceuticals-c-e-ferulic-with-15-l-ascorbic-acid'
  },
  {
    id: 'prod-ordinary-alpha-arbutin',
    productName: 'The Ordinary Alpha Arbutin 2% + HA',
    brand: 'The Ordinary',
    name: 'Alpha Arbutin 2% + HA',
    description_fr: 'Sérum concentré ciblant la pigmentation pour réduire les taches brunes et le teint irrégulier.',
    description_en: 'Concentrated serum targeting pigmentation to reduce dark spots and uneven skin tone.',
    price: '11€ - 14€',
    price_range: '€11–14',
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=240&auto=format&fit=crop',
    concerns: ['hyperpigmentation', 'radiance', 'dark_spots'],
    skinTypes: ['dry', 'normal', 'combination', 'oily', 'sensitive'],
    routineStep: 'serum',
    actives: ['Alpha Arbutine 2%', 'Acide Hyaluronique'],
    actives_en: ['Alpha Arbutin 2%', 'Hyaluronic Acid'],
    rating: 4.5,
    count: '9k+',
    efficacyLabel_fr: '90% taches pigmentaires atténuées',
    efficacyLabel_en: '90% hyperpigmentation marks faded',
    amazonLink: 'https://www.amazon.fr/dp/B071WNRQJY?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/the-ordinary-alpha-arbutin-2-ha'
  },
  {
    id: 'prod-laroche-retinol-b3',
    productName: 'La Roche-Posay Retinol B3 Serum',
    brand: 'La Roche-Posay',
    name: 'Retinol B3 Serum',
    description_fr: 'Régénère la peau en surface, réduit les rides profondes et unifie le teint des peaux sensibles.',
    description_en: 'Resurfaces skin, targets deep wrinkles and evens out sensitive skin complexions.',
    price: '38€ - 45€',
    price_range: '€38–45',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=240&auto=format&fit=crop',
    concerns: ['aging', 'texture', 'dark_spots'],
    skinTypes: ['dry', 'normal', 'combination', 'sensitive'],
    routineStep: 'serum',
    actives: ['Rétinol pur & à libération graduelle', 'Vitamine B3 (Niacinamide)'],
    actives_en: ['Pure & Gradual Retinol', 'Vitamin B3 (Niacinamide)'],
    rating: 4.7,
    count: '7k+',
    efficacyLabel_fr: '92% rides et ridules réduites',
    efficacyLabel_en: '92% reduced wrinkles and fine lines',
    amazonLink: 'https://www.amazon.fr/dp/B085V5JFSN?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/retinol-b3---serum-anti-rides-regenerant-unifiant-P4075107.html'
  },
  {
    id: 'prod-caudalie-vinoperfect-serum',
    productName: 'Caudalie Vinoperfect Serum',
    brand: 'Caudalie',
    name: 'Vinoperfect Radiance Dark Spot Serum',
    description_fr: 'Sérum culte anti-taches formulé pour booster l\'éclat et corriger la pigmentation cutanée.',
    description_en: 'Cult dark spot serum formulated to boost skin radiance and correct uneven pigmentation.',
    price: '46€ - 52€',
    price_range: '€46–52',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=240&auto=format&fit=crop',
    concerns: ['dark_spots', 'radiance', 'hyperpigmentation'],
    skinTypes: ['dry', 'normal', 'combination', 'oily', 'sensitive'],
    routineStep: 'serum',
    actives: ['Viniférine 1000ppm', 'Squalane d\'olive'],
    actives_en: ['Viniferine 1000ppm', 'Olive Squalane'],
    rating: 4.8,
    count: '14k+',
    efficacyLabel_fr: '93% taches corrigées après 1 flacon',
    efficacyLabel_en: '93% dark spots corrected after 1 bottle',
    amazonLink: 'https://www.amazon.fr/dp/B0053P2Q86?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/serum-eclat-anti-taches-vinoperfect-P5104.html'
  },

  // ── CATEGORY: MOISTURIZER (Crèmes & Hydratants) ──
  {
    id: 'prod-cerave-moisturising-cream',
    productName: 'CeraVe Moisturising Cream',
    brand: 'CeraVe',
    name: 'Moisturising Cream',
    description_fr: 'Formule riche non grasse aux 3 céramides essentiels et acide hyaluronique pour nourrir intensément.',
    description_en: 'Rich, non-greasy formula with 3 essential ceramides and hyaluronic acid for deep nourishment.',
    price: '12€ - 18€',
    price_range: '€12–18',
    imageUrl: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=240&auto=format&fit=crop',
    concerns: ['dryness', 'redness'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    routineStep: 'moisturizer',
    actives: ['Céramides', 'Acide Hyaluronique'],
    actives_en: ['Ceramides', 'Hyaluronic Acid'],
    rating: 4.8,
    count: '35k+',
    efficacyLabel_fr: '95% barrière cutanée renforcée',
    efficacyLabel_en: '95% skin barrier strengthened',
    amazonLink: 'https://www.amazon.fr/dp/B00TTD9BRC?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/cerave-moisturizing-cream'
  },
  {
    id: 'prod-laroche-effaclar-duo',
    productName: 'La Roche-Posay Effaclar Duo+M',
    brand: 'La Roche-Posay',
    name: 'Effaclar Duo+M Anti-Imperfections Care',
    description_fr: 'Soin triple correction anti-imperfections qui combat les boutons, marques rouges et pores bouchés.',
    description_en: 'Triple correction anti-imperfection care targeting spots, red marks, and clogged pores.',
    price: '15€ - 18€',
    price_range: '€15–18',
    imageUrl: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=240&auto=format&fit=crop',
    concerns: ['acne', 'pores'],
    skinTypes: ['oily', 'combination'],
    routineStep: 'moisturizer',
    actives: ['Phylobioma', 'Niacinamide', 'LHA & Acide Salicylique'],
    actives_en: ['Phylobioma', 'Niacinamide', 'LHA & Salicylic Acid'],
    rating: 4.7,
    count: '12k+',
    efficacyLabel_fr: '88% boutons réduits dès 12h',
    efficacyLabel_en: '88% breakouts reduced from 12 hours',
    amazonLink: 'https://www.amazon.fr/dp/B0CNZ3LDRM?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/effaclar-duo%2B-m---soin-triple-correction-anti-imperfections-P10056972.html'
  },
  {
    id: 'prod-clinique-moisture-surge',
    productName: 'Clinique Moisture Surge 100H',
    brand: 'Clinique',
    name: 'Moisture Surge 100H Auto-Replenishing Hydrator',
    description_fr: 'Un gel-crème frais sans huile qui pénètre en profondeur pour une hydratation continue longue durée.',
    description_en: 'An oil-free fresh gel-cream that penetrates deeply for long-lasting continuous hydration.',
    price: '32€ - 45€',
    price_range: '€32–45',
    imageUrl: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=240&auto=format&fit=crop',
    concerns: ['dryness', 'redness'],
    skinTypes: ['dry', 'normal', 'combination', 'sensitive', 'oily'],
    routineStep: 'moisturizer',
    actives: ['Bio-ferment d\'Aloe Vera', 'Acide Hyaluronique'],
    actives_en: ['Aloe Bio-ferment', 'Hyaluronic Acid'],
    rating: 4.7,
    count: '11k+',
    efficacyLabel_fr: '94% peau repulpée et lumineuse',
    efficacyLabel_en: '94% plumper and glowing skin',
    amazonLink: 'https://www.amazon.fr/dp/B08XMWWMR1?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/moisture-surge-100h---soin-auto-rehydratant-P4503025.html'
  },
  {
    id: 'prod-avene-cicalfate',
    productName: 'Avene Cicalfate+ Protective Cream',
    brand: 'Avene',
    name: 'Cicalfate+ Restorative Protective Cream',
    description_fr: 'Soin légendaire SOS qui apaise, répare et purifie les peaux irritées, abîmées ou réactives.',
    description_en: 'Legendary SOS cream that soothes, repairs, and purifies irritated, damaged, or reactive skin.',
    price: '9€ - 13€',
    price_range: '€9–13',
    imageUrl: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=240&auto=format&fit=crop',
    concerns: ['redness', 'dryness'],
    skinTypes: ['sensitive', 'dry', 'normal', 'combination'],
    routineStep: 'moisturizer',
    actives: ['[C+-Restore] (réparateur)', 'Sulfate de Cuivre & Zinc (purifiant)'],
    actives_en: ['[C+-Restore] (repairing)', 'Copper & Zinc Sulfate (purifying)'],
    rating: 4.8,
    count: '19k+',
    efficacyLabel_fr: '97% apaisement immédiat',
    efficacyLabel_en: '97% immediate soothing',
    amazonLink: 'https://www.amazon.fr/dp/B07YXYJ5R5?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/cicalfate%2B---creme-protectrice-restauratrice-peaux-sensibles-irritees-P3938012.html'
  },
  {
    id: 'prod-weleda-skin-food-light',
    productName: 'Weleda Skin Food Light',
    brand: 'Weleda',
    name: 'Skin Food Light',
    description_fr: 'Soin hydratant multifonctions à absorption rapide qui nourrit intensément les peaux sèches et donne un teint dewy.',
    description_en: 'Fast-absorbing multi-purpose moisturizer that deeply nourishes dry skin and provides a dewy glow.',
    price: '10€ - 14€',
    price_range: '€10–14',
    imageUrl: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=240&auto=format&fit=crop',
    concerns: ['dryness', 'radiance'],
    skinTypes: ['dry', 'normal', 'combination'],
    routineStep: 'moisturizer',
    actives: ['Pensée Sauvage', 'Camomille', 'Calendula'],
    actives_en: ['Wild Pansy', 'Chamomile Extract', 'Calendula Extract'],
    rating: 4.6,
    count: '14k+',
    efficacyLabel_fr: '92% nutrition intense de la peau',
    efficacyLabel_en: '92% intense skin nourishment',
    amazonLink: 'https://www.amazon.fr/dp/B07KGP4B2P?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/weleda-skin-food-light-nourishing-cream-P469372'
  },

  // ── CATEGORY: SUNSCREEN (Protections Solaires SPF) ──
  {
    id: 'prod-laroche-anthelios',
    productName: 'La Roche-Posay Anthelios UVMune 400 Fluid SPF50+',
    brand: 'La Roche-Posay',
    name: 'Anthelios UVMune 400 Invisible Fluid SPF50+',
    description_fr: 'Fluide solaire invisible au fini mat offrant la plus haute protection contre les rayons UVA longs dégradant la peau.',
    description_en: 'Invisible solar fluid with a matte finish offering ultimate protection against skin-degrading long UVA rays.',
    price: '16€ - 20€',
    price_range: '€16–20',
    imageUrl: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=240&auto=format&fit=crop',
    concerns: ['aging', 'dark_spots', 'redness'],
    skinTypes: ['dry', 'normal', 'combination', 'oily', 'sensitive'],
    routineStep: 'sunscreen',
    actives: ['Mexoryl 400 (filtre UV)', 'Eau Thermale'],
    actives_en: ['Mexoryl 400 (UV filter)', 'Thermal Spring Water'],
    rating: 4.8,
    count: '15k+',
    efficacyLabel_fr: '99% prévention photo-vieillissement',
    efficacyLabel_en: '99% photo-aging prevention',
    amazonLink: 'https://www.amazon.fr/dp/B09V7SDF7X?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/anthelios-uvmune-400---fluide-invisible-sans-parfum-spf50%2B-P10023812.html'
  },
  {
    id: 'prod-beauty-of-joseon-relief-sun',
    productName: 'Beauty of Joseon Relief Sun SPF50+',
    brand: 'Beauty of Joseon',
    name: 'Relief Sun : Rice + Probiotics SPF50+',
    description_fr: 'Crème solaire coréenne bio ultra-légère et apaisante qui nourrit et illumine sans laisser de traces blanches.',
    description_en: 'Soothing organic Korean sunscreen that nourishes and brightens without leaving any white cast.',
    price: '15€ - 19€',
    price_range: '€15–19',
    imageUrl: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=240&auto=format&fit=crop',
    concerns: ['redness', 'dryness', 'radiance'],
    skinTypes: ['dry', 'normal', 'combination', 'sensitive'],
    routineStep: 'sunscreen',
    actives: ['Extrait de Riz 30%', 'Probiotiques'],
    actives_en: ['Rice Extract 30%', 'Grain Fermented Probiotics'],
    rating: 4.8,
    count: '18k+',
    efficacyLabel_fr: '95% peau hydratée et douce au fini frais',
    efficacyLabel_en: '95% hydrated skin with a fresh dewy finish',
    amazonLink: 'https://www.amazon.fr/dp/B09JVKB925?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/beauty-of-joseon-relief-sun-rice-probiotics-spf50'
  },
  {
    id: 'prod-biore-uv-aqua-rich',
    productName: 'Bioré UV Aqua Rich Watery Essence SPF50+',
    brand: 'Bioré',
    name: 'UV Aqua Rich Watery Essence',
    description_fr: 'Une essence solaire japonaise culte, ultra-fraîche comme de l\'eau, qui pénètre instantanément sans fini gras.',
    description_en: 'Cult Japanese watery solar essence, ultra-light and hydrating, absorbing instantly with zero greasy finish.',
    price: '14€ - 18€',
    price_range: '€14–18',
    imageUrl: 'https://images.unsplash.com/photo-1608248597481-496100c80836?q=80&w=240&auto=format&fit=crop',
    concerns: ['pores', 'dryness'],
    skinTypes: ['oily', 'combination', 'normal'],
    routineStep: 'sunscreen',
    actives: ['Acide Hyaluronique', 'Extrait de Gelée Royale'],
    actives_en: ['Hyaluronic Acid', 'Royal Jelly Extract'],
    rating: 4.7,
    count: '22k+',
    efficacyLabel_fr: '94% effet fraîcheur aqueuse ressenti',
    efficacyLabel_en: '94% refreshing watery texture felt',
    amazonLink: 'https://www.amazon.fr/dp/B07MFX87LV?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/biore-uv-aqua-rich-watery-essence-spf-50'
  },

  // ── CATEGORY: MASK & NIGHT (Masques & Soins ciblés) ──
  {
    id: 'prod-laneige-water-sleeping-mask',
    productName: 'Laneige Water Sleeping Mask',
    brand: 'Laneige',
    name: 'Water Sleeping Mask',
    description_fr: 'Masque de nuit en gel qui infuse la peau d\'hydratation profonde pour un teint frais et reposé au réveil.',
    description_en: 'Overnight gel mask that replenishes deep skin hydration for a fresh, well-rested morning glow.',
    price: '28€ - 32€',
    price_range: '€25–32',
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=240&auto=format&fit=crop',
    concerns: ['dryness', 'radiance'],
    skinTypes: ['dry', 'normal', 'sensitive', 'combination', 'oily'],
    routineStep: 'mask',
    actives: ['Probiotiques complexes', 'Squalane', 'Acide Hyaluronique'],
    actives_en: ['Complex Probiotics', 'Squalane', 'Hyaluronic Acid'],
    rating: 4.7,
    count: '12k+',
    efficacyLabel_fr: '93% hydratation nocturne intense',
    efficacyLabel_en: '93% intense overnight hydration',
    amazonLink: 'https://www.amazon.fr/dp/B07HCP72JV?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/laneige-water-sleeping-mask-lavender'
  },
  {
    id: 'prod-caudalie-instant-detox',
    productName: 'Caudalie Vinergetic C+ Instant Detox Mask',
    brand: 'Caudalie',
    name: 'Vinergetic C+ Instant Detox Mask',
    description_fr: 'Masque d\'argile rose qui élimine les toxines, resserre visiblement les pores et ravive le teint terne.',
    description_en: 'Pink clay mask that draws out skin impurities, tightens pores, and revives dull complexions.',
    price: '22€ - 26€',
    price_range: '€22–26',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=240&auto=format&fit=crop',
    concerns: ['pores', 'acne', 'radiance'],
    skinTypes: ['oily', 'combination', 'normal'],
    routineStep: 'mask',
    actives: ['Argile Rose', 'Marc de Raisin', 'Caféine'],
    actives_en: ['Pink Clay', 'Grape Marc', 'Caffeine'],
    rating: 4.6,
    count: '8k+',
    efficacyLabel_fr: '91% pores resserrés immédiatement',
    efficacyLabel_en: '91% pores tightened immediately',
    amazonLink: 'https://www.amazon.fr/dp/B08XMS7KFF?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/masque-instant-detox-vinergetic-c%2B-P4483030.html'
  },

  // ── CATEGORY: EYE CARE (Contour des Yeux) ──
  {
    id: 'prod-inkeylist-caffeine-eye',
    productName: 'The Inkey List Caffeine Eye Cream',
    brand: 'The Inkey List',
    name: 'Caffeine Eye Cream',
    description_fr: 'Légère et hydratante, elle réduit instantanément le gonflement et les cernes sous les yeux.',
    description_en: 'Lightweight and hydrating, it targets puffiness and dark circles around the eye contour area.',
    price: '11€ - 14€',
    price_range: '€10–14',
    imageUrl: 'https://images.unsplash.com/photo-1629732047847-50b7ecf0cbf1?q=80&w=240&auto=format&fit=crop',
    concerns: ['dark_circles', 'redness'],
    skinTypes: ['dry', 'normal', 'combination', 'oily', 'sensitive'],
    routineStep: 'eye',
    actives: ['Caféine', 'Peptide Matrixyl 3000'],
    actives_en: ['Caffeine', 'Matrixyl 3000 Peptide'],
    rating: 4.4,
    count: '10k+',
    efficacyLabel_fr: '88% gonflement & cernes estompés',
    efficacyLabel_en: '88% puffiness & dark circles reduced',
    amazonLink: 'https://www.amazon.fr/dp/B08JH2JH7Y?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/the-inkey-list-caffeine-eye-cream'
  },
  {
    id: 'prod-kiehls-avocado-eye',
    productName: "Kiehl's Creamy Eye Treatment with Avocado",
    brand: "Kiehl's",
    name: 'Creamy Eye Treatment with Avocado',
    description_fr: 'Soin extrêmement nourrissant qui hydrate en profondeur la zone délicate sous l\'œil et lisse les ridules.',
    description_en: 'Rich creamy avocado formula that deeply hydrates and softens the delicate under-eye area.',
    price: '32€ - 42€',
    price_range: '€28–36',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?q=80&w=240&auto=format&fit=crop',
    concerns: ['dark_circles', 'dryness', 'aging'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    routineStep: 'eye',
    actives: ['Huile d\'Avocat', 'Bêta-Carotène', 'Beurre de Karité'],
    actives_en: ['Avocado Oil', 'Beta-Carotene', 'Shea Butter'],
    rating: 4.7,
    count: '6k+',
    efficacyLabel_fr: '92% contour de l\'œil souple et hydraté',
    efficacyLabel_en: '92% soft and deeply moisturized eye contour',
    amazonLink: 'https://www.amazon.fr/dp/B000G0WVKA?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.com/product/kiehls-creamy-eye-treatment-with-avocado'
  },
  {
    id: 'prod-cerave-eye-repair',
    productName: 'CeraVe Eye Repair Cream',
    brand: 'CeraVe',
    name: 'Eye Repair Cream',
    description_fr: 'Réduit l\'apparence des cernes et des poches tout en restaurant la barrière protectrice du contour de l\'œil.',
    description_en: 'Reduces the appearance of dark circles and puffiness while restoring the delicate eye area barrier.',
    price: '13€ - 17€',
    price_range: '€13–17',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?q=80&w=240&auto=format&fit=crop',
    concerns: ['dark_circles', 'redness', 'dryness'],
    skinTypes: ['dry', 'normal', 'combination', 'sensitive'],
    routineStep: 'eye',
    actives: ['Céramides', 'Acide Hyaluronique', 'Complexe Marin'],
    actives_en: ['Ceramides', 'Hyaluronic Acid', 'Marine & Botanical Complex'],
    rating: 4.6,
    count: '15k+',
    efficacyLabel_fr: '89% regard plus frais et reposé',
    efficacyLabel_en: '89% fresher, more rested look',
    amazonLink: 'https://www.amazon.fr/dp/B00T725EQW?tag=ratemyskin-21',
    sephoraLink: 'https://www.sephora.fr/p/creme-contour-des-yeux---anti-cernes-et-anti-poches-P3575003.html'
  }
];
