import { useRouter } from 'next/router';
import Head from 'next/head';
import Logo from '../components/Logo';
import { useLang } from '../lib/LangContext';

function LangToggle() {
  const { lang, setLang } = useLang();
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 2 }}>
      {['en', 'fr'].map((l, i) => (
        <span key={l} style={{ display: 'flex', alignItems: 'center', gap: 2 }}>
          {i > 0 && <span style={{ color: '#ddd', fontSize: 11, lineHeight: 1 }}>|</span>}
          <button
            onClick={() => setLang(l)}
            style={{
              background: 'none', border: 'none',
              fontSize: 11, fontWeight: lang === l ? 700 : 400,
              color: lang === l ? '#0d0d0d' : '#bbb',
              cursor: 'pointer', padding: '2px 5px',
              fontFamily: "'DM Sans', sans-serif",
              letterSpacing: '0.1em',
              textTransform: 'uppercase',
            }}
          >
            {l.toUpperCase()}
          </button>
        </span>
      ))}
    </div>
  );
}

const content = {
  fr: {
    title: 'Avertissement médical',
    lastUpdated: 'Dernière mise à jour : 21 mai 2026',
    intro: "Rate My Skin utilise l'intelligence artificielle pour analyser des photos de peau à des fins d'information générale. Veuillez lire attentivement cet avertissement avant d'utiliser notre service.",
    sections: [
      {
        title: "1. Pas un diagnostic médical",
        body: "Cette analyse N'EST PAS un diagnostic médical. Les résultats fournis par Rate My Skin sont générés par un modèle d'intelligence artificielle et ont une valeur purement indicative. Ils ne constituent en aucun cas un avis médical, un diagnostic ou une prescription.",
      },
      {
        title: "2. Limites de l'IA",
        body: "L'intelligence artificielle peut commettre des erreurs, mal interpréter des éléments visuels ou ne pas détecter des conditions dermatologiques sérieuses, notamment les mélanomes, les carcinomes ou d'autres pathologies cutanées nécessitant une évaluation clinique en présentiel.",
      },
      {
        title: "3. Consultez un professionnel de santé",
        body: "Pour des conditions de peau sérieuses — mélanome, eczéma sévère, acné kystique, psoriasis, rosacée ou toute lésion suspecte — consultez IMPÉRATIVEMENT un dermatologue ou un médecin. Aucune décision médicale ne doit être prise sur la seule base de cette analyse.\n\nEn cas d'urgence médicale, appelez le 15 (SAMU, France) ou votre service d'urgence local.",
      },
      {
        title: "4. Recommandations produits",
        body: "Les recommandations de produits cosmétiques sont basées sur les résultats de l'IA et ne tiennent pas compte de vos allergies, sensibilités ou conditions médicales spécifiques. Effectuez toujours un test de tolérance cutané avant d'utiliser un nouveau produit. En cas de doute, consultez un dermatologue ou un allergologue.",
      },
      {
        title: "5. Limitation de responsabilité",
        body: "Rate My Skin, ses créateurs et prestataires techniques déclinent toute responsabilité en cas de réaction allergique, d'aggravation de symptômes, de diagnostic manqué ou de tout autre préjudice résultant de l'utilisation de ce service. L'utilisateur utilise ce service à ses propres risques et sous sa propre responsabilité.",
      },
      {
        title: "6. Acceptation des conditions",
        body: "En utilisant Rate My Skin, vous reconnaissez avoir lu et accepté cet avertissement. Vous confirmez que les résultats obtenus sont utilisés à titre d'information générale uniquement et non à des fins médicales.",
      },
    ],
    back: '← Retour à l\'accueil',
  },
  en: {
    title: 'Medical Disclaimer',
    lastUpdated: 'Last updated: May 21, 2026',
    intro: "Rate My Skin uses artificial intelligence to analyze skin photos for general informational purposes. Please read this disclaimer carefully before using our service.",
    sections: [
      {
        title: "1. Not a Medical Diagnosis",
        body: "This analysis IS NOT a medical diagnosis. Results provided by Rate My Skin are generated by an AI model and are purely indicative. They do not constitute medical advice, a diagnosis, or a prescription of any kind.",
      },
      {
        title: "2. Limitations of AI",
        body: "Artificial intelligence can make errors, misinterpret visual elements, or fail to detect serious dermatological conditions — including melanoma, carcinoma, or other skin pathologies that require in-person clinical evaluation.",
      },
      {
        title: "3. Consult a Healthcare Professional",
        body: "For serious skin conditions — melanoma, severe eczema, cystic acne, psoriasis, rosacea, or any suspicious lesion — you MUST consult a dermatologist or physician. No medical decision should be made based solely on this analysis.\n\nIn case of a medical emergency, call your local emergency services (911 in the US, 15 in France, 999 in the UK).",
      },
      {
        title: "4. Product Recommendations",
        body: "Skincare product recommendations are based on AI results and do not account for your specific allergies, sensitivities, or medical conditions. Always perform a skin patch test before using a new product. When in doubt, consult a dermatologist or allergist.",
      },
      {
        title: "5. Limitation of Liability",
        body: "Rate My Skin, its creators, and technical providers disclaim all liability for allergic reactions, worsening of symptoms, missed diagnoses, or any other harm resulting from the use of this service. Users use this service at their own risk and responsibility.",
      },
      {
        title: "6. Acceptance of Terms",
        body: "By using Rate My Skin, you acknowledge that you have read and accepted this disclaimer. You confirm that the results obtained are used for general informational purposes only and not for medical purposes.",
      },
    ],
    back: '← Back to Home',
  },
};

export default function MentionsLegales() {
  const router = useRouter();
  const { lang } = useLang();
  const active = content[lang] || content.fr;

  return (
    <>
      <Head>
        <title>{active.title} — Rate My Skin</title>
        <meta name="description" content={lang === 'fr'
          ? "Avertissement médical de Rate My Skin. Cette analyse IA n'est pas un diagnostic médical."
          : "Medical disclaimer for Rate My Skin. This AI analysis is not a medical diagnosis."
        } />
        <meta name="robots" content="noindex, follow" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="canonical" href="https://ratemyskin.co/mentions-legales" />
      </Head>

      {/* Sticky nav */}
      <div className="nav-blur" style={{
        position: 'sticky', top: 0, zIndex: 100,
        padding: '13px 26px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        animation: 'slideDown 0.55s ease',
      }}>
        <Logo />
        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <LangToggle />
          <button
            onClick={() => router.push('/')}
            className="btn-liquid-glass"
            style={{ borderRadius: 10, padding: '9px 18px', fontSize: 12, border: 'none' }}
          >
            {active.back}
          </button>
        </div>
      </div>

      <div style={{ maxWidth: 720, margin: '40px auto 80px', padding: '0 24px' }}>
        <div className="card-blur" style={{
          borderRadius: 24,
          padding: 'clamp(24px, 5vw, 48px)',
          boxShadow: '0 12px 48px rgba(168,116,73,0.06), inset 0 1px 0 rgba(255,255,255,0.9)',
          animation: 'scaleIn 0.5s ease-out',
        }}>
          {/* Warning pill */}
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 24 }}>
            <span style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              background: 'rgba(168, 116, 73, 0.08)',
              border: '1px solid rgba(168, 116, 73, 0.22)',
              borderRadius: 30, padding: '5px 14px',
              fontSize: 10, fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase',
              color: '#A87449', fontFamily: "'DM Sans', sans-serif",
            }}>
              ℹ {lang === 'fr' ? 'Information importante' : 'Important information'}
            </span>
          </div>

          <h1 style={{
            fontFamily: "'Cormorant Garamond', serif",
            fontSize: 'clamp(28px, 6vw, 42px)',
            fontWeight: 400,
            color: '#3A2E26',
            marginBottom: 8,
            lineHeight: 1.2,
            textAlign: 'center',
          }}>
            {active.title}
          </h1>

          <p style={{
            fontSize: 12,
            color: '#A87449',
            fontFamily: "'DM Sans', sans-serif",
            letterSpacing: '0.04em',
            marginBottom: 24,
            textAlign: 'center',
          }}>
            {active.lastUpdated}
          </p>

          <p style={{
            fontSize: 14.5,
            lineHeight: 1.75,
            color: '#6F6156',
            marginBottom: 32,
            fontFamily: "'DM Sans', sans-serif",
          }}>
            {active.intro}
          </p>

          <div style={{ height: '1px', background: 'linear-gradient(90deg, transparent, rgba(168,116,73,0.15), transparent)', marginBottom: 32 }} />

          <div style={{ display: 'flex', flexDirection: 'column', gap: 28 }}>
            {active.sections.map((section, idx) => (
              <div key={idx}>
                <h2 style={{
                  fontFamily: "'Cormorant Garamond', serif",
                  fontSize: 22,
                  fontWeight: 500,
                  color: '#3A2E26',
                  marginBottom: 10,
                }}>
                  {section.title}
                </h2>
                <p style={{
                  fontSize: 13.5,
                  lineHeight: 1.7,
                  color: '#6F6156',
                  fontFamily: "'DM Sans', sans-serif",
                  whiteSpace: 'pre-line',
                  margin: 0,
                }}>
                  {section.body}
                </p>
              </div>
            ))}
          </div>

          <div style={{ height: '1px', background: 'linear-gradient(90deg, transparent, rgba(168,116,73,0.15), transparent)', marginTop: 40, marginBottom: 32 }} />

          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <button
              onClick={() => router.push('/')}
              className="btn-liquid-glass-dark"
              style={{
                borderRadius: 12,
                padding: '14px 28px',
                fontSize: 13,
                fontWeight: 600,
                border: 'none',
              }}
            >
              {active.back}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
